//! Weights for `pallet_storage_lifecycle`
//!
//! Weights estimated from worst-case DB access analysis (reads/writes per extrinsic).
//! NOT auto-generated by the benchmark CLI — replace with real measurements before mainnet.
//!
//! Run `cargo run --release --features runtime-benchmarks -- benchmark pallet`
//! to regenerate with actual hardware measurements.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions for `pallet_storage_lifecycle` based on worst-case DB access analysis.
///
/// Per-extrinsic breakdown:
/// - Reads/writes counted by tracing every StorageMap/StorageValue access
/// - proof_size estimated as MaxEncodedLen of accessed storage items
/// - compute (ref_time) estimated conservatively from O(n) loops + hashing
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> super::WeightInfo for SubstrateWeight<T> {
    // set_archive_config: 1 read (ArchiveConfigOverride) + 1 write (ArchiveConfigOverride) + event
    fn set_archive_config() -> Weight {
        Weight::from_parts(15_000_000, 2_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // pause_archival: 1 read (ArchivalPaused) + 1 write (ArchivalPaused) + event
    fn pause_archival() -> Weight {
        Weight::from_parts(10_000_000, 1_500)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // resume_archival: 1 read (ArchivalPaused) + 1 write (ArchivalPaused) + event
    fn resume_archival() -> Weight {
        Weight::from_parts(10_000_000, 1_500)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // set_archive_policy: 1 write (ArchivePolicies) + event
    fn set_archive_policy() -> Weight {
        Weight::from_parts(15_000_000, 2_000)
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // force_archive: worst case 100 items — per item: 1 read (DataArchiveStatus) + 1 write (DataArchiveStatus)
    //   + 1 write (ActiveExtensions remove) + conditional PurgeProtected remove
    //   + StorageArchiver::archive_to_level + OnArchive callback
    fn force_archive() -> Weight {
        Weight::from_parts(150_000_000, 15_000)
            .saturating_add(T::DbWeight::get().reads(100))
            .saturating_add(T::DbWeight::get().writes(300))
    }

    // protect_from_purge: 1 read (PurgeProtected) + 1 write (PurgeProtected) + event
    fn protect_from_purge() -> Weight {
        Weight::from_parts(12_000_000, 2_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // remove_purge_protection: 1 read (PurgeProtected) + 1 write (PurgeProtected remove) + event
    fn remove_purge_protection() -> Weight {
        Weight::from_parts(12_000_000, 2_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // extend_active_period: 2 reads (DataArchiveStatus, ActiveExtensions) + 1 write (ActiveExtensions) + event
    fn extend_active_period() -> Weight {
        Weight::from_parts(15_000_000, 2_500)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // restore_from_archive: 1 read (DataArchiveStatus) + 1 write (DataArchiveStatus)
    //   + StorageArchiver::restore_record + OnArchive callback + event
    fn restore_from_archive() -> Weight {
        Weight::from_parts(50_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
}

/// For testing — uses RocksDbWeight defaults
impl super::WeightInfo for () {
    fn set_archive_config() -> Weight {
        Weight::from_parts(15_000_000, 2_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn pause_archival() -> Weight {
        Weight::from_parts(10_000_000, 1_500)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn resume_archival() -> Weight {
        Weight::from_parts(10_000_000, 1_500)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn set_archive_policy() -> Weight {
        Weight::from_parts(15_000_000, 2_000)
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn force_archive() -> Weight {
        Weight::from_parts(150_000_000, 15_000)
            .saturating_add(RocksDbWeight::get().reads(100))
            .saturating_add(RocksDbWeight::get().writes(300))
    }
    fn protect_from_purge() -> Weight {
        Weight::from_parts(12_000_000, 2_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn remove_purge_protection() -> Weight {
        Weight::from_parts(12_000_000, 2_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn extend_active_period() -> Weight {
        Weight::from_parts(15_000_000, 2_500)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn restore_from_archive() -> Weight {
        Weight::from_parts(50_000_000, 5_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
}
