//! Autogenerated weights for `pallet_commission_core`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-03-07, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `nexus-bench-01`, CPU: `Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/production/nexus-node
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_commission_core
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --output=pallets/entity/commission/core/src/weights.rs
// --template=.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_commission_core`.
pub trait WeightInfo {
    fn set_commission_modes() -> Weight;
    fn set_commission_rate() -> Weight;
    fn enable_commission() -> Weight;
    fn withdraw_commission() -> Weight;
    fn set_withdrawal_config() -> Weight;
    fn use_shopping_balance() -> Weight;
    fn init_commission_plan() -> Weight;
    fn withdraw_token_commission() -> Weight;
    fn set_token_withdrawal_config() -> Weight;
    fn set_global_min_token_repurchase_rate() -> Weight;
    fn withdraw_entity_funds() -> Weight;
    fn withdraw_entity_token_funds() -> Weight;
    fn set_creator_reward_rate() -> Weight;
    fn set_token_platform_fee_rate() -> Weight;
    fn set_global_min_repurchase_rate() -> Weight;
    fn set_withdrawal_cooldown() -> Weight;
    fn force_disable_entity_commission() -> Weight;
    fn set_global_max_commission_rate() -> Weight;
    fn clear_commission_config() -> Weight;
    fn clear_withdrawal_config() -> Weight;
    fn clear_token_withdrawal_config() -> Weight;
    fn set_global_max_token_commission_rate() -> Weight;
    fn force_global_pause() -> Weight;
    fn pause_withdrawals() -> Weight;
    fn archive_order_records() -> Weight;
    fn force_enable_entity_commission() -> Weight;
    fn retry_cancel_commission() -> Weight;
    fn set_min_withdrawal_interval() -> Weight;
}

/// Weights for `pallet_commission_core` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_active` (r:1 w:0)
    /// Storage: `CommissionConfigs` (r:1 w:1)
    /// Storage: `PoolRewardDisabledAt` (r:1 w:1)
    fn set_commission_modes() -> Weight {
        Weight::from_parts(42_318_000, 4_096)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_active` (r:1 w:0)
    /// Storage: `GlobalMaxCommissionRate` (r:1 w:0)
    /// Storage: `GlobalMaxTokenCommissionRate` (r:1 w:0)
    /// Storage: `CommissionConfigs` (r:1 w:1)
    fn set_commission_rate() -> Weight {
        Weight::from_parts(43_527_000, 4_096)
            .saturating_add(T::DbWeight::get().reads(6_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_active` (r:1 w:0)
    /// Storage: `CommissionConfigs` (r:2 w:1)
    /// Storage: `PoolRewardDisabledAt` (r:0 w:1)
    fn enable_commission() -> Weight {
        Weight::from_parts(40_215_000, 4_096)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: `GlobalCommissionPaused` (r:1 w:0)
    /// Storage: `WithdrawalPaused` (r:1 w:0)
    /// Storage: `MemberCommissionStats` (r:1 w:1)
    /// Storage: `WithdrawalConfigs` (r:1 w:0)
    /// Storage: `CommissionConfigs` (r:1 w:0)
    /// Storage: `MemberLastCredited` (r:1 w:0)
    /// Storage: `MinWithdrawalInterval` (r:1 w:0)
    /// Storage: `MemberLastWithdrawn` (r:1 w:1)
    /// Storage: `GlobalMinRepurchaseRate` (r:1 w:0)
    /// Storage: `ShopPendingTotal` (r:1 w:1)
    /// Storage: `ShopShoppingTotal` (r:1 w:1)
    /// Storage: `UnallocatedPool` (r:1 w:0)
    /// Storage: `MemberShoppingBalance` (r:1 w:1)
    /// Storage: `MemberWithdrawalHistory` (r:1 w:1)
    /// Storage: `EntityProvider::entity_account` (r:1 w:0)
    /// Storage: `Currency::free_balance` (r:1 w:1)
    fn withdraw_commission() -> Weight {
        Weight::from_parts(89_743_000, 6_144)
            .saturating_add(T::DbWeight::get().reads(16_u64))
            .saturating_add(T::DbWeight::get().writes(7_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_active` (r:1 w:0)
    /// Storage: `WithdrawalConfigs` (r:0 w:1)
    fn set_withdrawal_config() -> Weight {
        Weight::from_parts(48_632_000, 5_120)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// [已禁用] 立即返回错误
    fn use_shopping_balance() -> Weight {
        Weight::from_parts(8_124_000, 1_024)
    }

    /// [已禁用] 立即返回错误
    fn init_commission_plan() -> Weight {
        Weight::from_parts(8_124_000, 1_024)
    }

    /// Storage: `GlobalCommissionPaused` (r:1 w:0)
    /// Storage: `WithdrawalPaused` (r:1 w:0)
    /// Storage: `MemberTokenCommissionStats` (r:1 w:1)
    /// Storage: `TokenWithdrawalConfigs` (r:1 w:0)
    /// Storage: `CommissionConfigs` (r:1 w:0)
    /// Storage: `MemberTokenLastCredited` (r:1 w:0)
    /// Storage: `MinWithdrawalInterval` (r:1 w:0)
    /// Storage: `MemberTokenLastWithdrawn` (r:1 w:1)
    /// Storage: `GlobalMinTokenRepurchaseRate` (r:1 w:0)
    /// Storage: `TokenPendingTotal` (r:1 w:1)
    /// Storage: `LoyaltyToken::token_shopping_total` (r:1 w:1) [via Port]
    /// Storage: `UnallocatedTokenPool` (r:1 w:0)
    /// Storage: `LoyaltyToken::token_shopping_balance` (r:1 w:1) [via Port]
    /// Storage: `MemberTokenWithdrawalHistory` (r:1 w:1)
    /// Storage: `EntityTokenAccountedBalance` (r:1 w:1)
    /// Storage: `TokenTransferProvider::token_balance_of` (r:1 w:0)
    fn withdraw_token_commission() -> Weight {
        Weight::from_parts(102_456_000, 8_192)
            .saturating_add(T::DbWeight::get().reads(16_u64))
            .saturating_add(T::DbWeight::get().writes(7_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_active` (r:1 w:0)
    /// Storage: `TokenWithdrawalConfigs` (r:0 w:1)
    fn set_token_withdrawal_config() -> Weight {
        Weight::from_parts(48_632_000, 5_120)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `GlobalMinTokenRepurchaseRate` (r:0 w:1)
    fn set_global_min_token_repurchase_rate() -> Weight {
        Weight::from_parts(18_743_000, 2_048)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `CommissionConfigs` (r:1 w:0)
    /// Storage: `UnallocatedPool` (r:1 w:1)
    /// Storage: `PoolRewardDisabledAt` (r:1 w:0)
    /// Storage: `ShopPendingTotal` (r:1 w:0)
    /// Storage: `ShopShoppingTotal` (r:1 w:0)
    /// Storage: `Currency::free_balance` (r:1 w:1)
    fn withdraw_entity_funds() -> Weight {
        Weight::from_parts(62_318_000, 5_120)
            .saturating_add(T::DbWeight::get().reads(8_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `EntityTokenAccountedBalance` (r:1 w:1)
    /// Storage: `UnallocatedTokenPool` (r:1 w:1)
    /// Storage: `PoolRewardDisabledAt` (r:1 w:0)
    /// Storage: `CommissionConfigs` (r:1 w:0)
    /// Storage: `TokenPendingTotal` (r:1 w:0)
    /// Storage: `LoyaltyToken::token_shopping_total` (r:1 w:0) [via Port]
    /// Storage: `TokenTransferProvider::token_balance_of` (r:1 w:0)
    fn withdraw_entity_token_funds() -> Weight {
        Weight::from_parts(65_127_000, 5_120)
            .saturating_add(T::DbWeight::get().reads(9_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `GovernanceProvider::governance_mode` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_active` (r:1 w:0)
    /// Storage: `CommissionConfigs` (r:1 w:1)
    fn set_creator_reward_rate() -> Weight {
        Weight::from_parts(41_832_000, 4_096)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `TokenPlatformFeeRate` (r:1 w:1)
    fn set_token_platform_fee_rate() -> Weight {
        Weight::from_parts(16_218_000, 2_048)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `GlobalMinRepurchaseRate` (r:0 w:1)
    fn set_global_min_repurchase_rate() -> Weight {
        Weight::from_parts(18_743_000, 2_048)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_active` (r:1 w:0)
    /// Storage: `CommissionConfigs` (r:1 w:1)
    fn set_withdrawal_cooldown() -> Weight {
        Weight::from_parts(39_527_000, 4_096)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `EntityProvider::entity_exists` (r:1 w:0)
    /// Storage: `CommissionConfigs` (r:1 w:1)
    /// Storage: `PoolRewardDisabledAt` (r:0 w:1)
    fn force_disable_entity_commission() -> Weight {
        Weight::from_parts(35_218_000, 3_072)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: `GlobalMaxCommissionRate` (r:0 w:1)
    fn set_global_max_commission_rate() -> Weight {
        Weight::from_parts(18_743_000, 2_048)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `CommissionConfigs` (r:1 w:1)
    /// Storage: `PoolRewardDisabledAt` (r:0 w:1)
    fn clear_commission_config() -> Weight {
        Weight::from_parts(38_124_000, 4_096)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `WithdrawalConfigs` (r:1 w:1)
    fn clear_withdrawal_config() -> Weight {
        Weight::from_parts(32_456_000, 3_584)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `TokenWithdrawalConfigs` (r:1 w:1)
    fn clear_token_withdrawal_config() -> Weight {
        Weight::from_parts(32_456_000, 3_584)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `GlobalMaxTokenCommissionRate` (r:0 w:1)
    fn set_global_max_token_commission_rate() -> Weight {
        Weight::from_parts(18_743_000, 2_048)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `GlobalCommissionPaused` (r:0 w:1)
    fn force_global_pause() -> Weight {
        Weight::from_parts(14_527_000, 1_536)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `WithdrawalPaused` (r:0 w:1)
    fn pause_withdrawals() -> Weight {
        Weight::from_parts(28_934_000, 3_072)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `OrderCommissionRecords` (r:1 w:1)
    /// Storage: `OrderTokenCommissionRecords` (r:1 w:1)
    /// Storage: `OrderTreasuryTransfer` (r:0 w:1)
    /// Storage: `OrderUnallocated` (r:0 w:1)
    /// Storage: `OrderTokenUnallocated` (r:0 w:1)
    /// Storage: `OrderTokenPlatformRetention` (r:0 w:1)
    fn archive_order_records() -> Weight {
        Weight::from_parts(58_743_000, 6_144)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(6_u64))
    }

    /// Storage: `EntityProvider::entity_exists` (r:1 w:0)
    /// Storage: `CommissionConfigs` (r:1 w:1)
    fn force_enable_entity_commission() -> Weight {
        Weight::from_parts(28_934_000, 3_072)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `OrderCommissionRecords` (r:1 w:1)
    /// Storage: `OrderTokenCommissionRecords` (r:1 w:1)
    /// Storage: `OrderTreasuryTransfer` (r:1 w:1)
    /// Storage: `OrderUnallocated` (r:1 w:1)
    /// Storage: `OrderTokenUnallocated` (r:1 w:1)
    /// Storage: `OrderTokenPlatformRetention` (r:1 w:1)
    /// Storage: `MemberCommissionStats` (r:n w:n)
    /// Storage: `ShopPendingTotal` (r:1 w:1)
    /// Storage: `UnallocatedPool` (r:1 w:1)
    /// Storage: `Currency::free_balance` (r:n w:n)
    fn retry_cancel_commission() -> Weight {
        Weight::from_parts(105_218_000, 8_192)
            .saturating_add(T::DbWeight::get().reads(10_u64))
            .saturating_add(T::DbWeight::get().writes(10_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_active` (r:1 w:0)
    /// Storage: `MinWithdrawalInterval` (r:0 w:1)
    fn set_min_withdrawal_interval() -> Weight {
        Weight::from_parts(28_934_000, 3_072)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
}

/// For testing — uses `()` with `RocksDbWeight`.
impl WeightInfo for () {
    fn set_commission_modes() -> Weight {
        Weight::from_parts(42_318_000, 4_096)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }

    fn set_commission_rate() -> Weight {
        Weight::from_parts(43_527_000, 4_096)
            .saturating_add(RocksDbWeight::get().reads(6_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn enable_commission() -> Weight {
        Weight::from_parts(40_215_000, 4_096)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }

    fn withdraw_commission() -> Weight {
        Weight::from_parts(89_743_000, 6_144)
            .saturating_add(RocksDbWeight::get().reads(16_u64))
            .saturating_add(RocksDbWeight::get().writes(7_u64))
    }

    fn set_withdrawal_config() -> Weight {
        Weight::from_parts(48_632_000, 5_120)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn use_shopping_balance() -> Weight {
        Weight::from_parts(8_124_000, 1_024)
    }

    fn init_commission_plan() -> Weight {
        Weight::from_parts(8_124_000, 1_024)
    }

    fn withdraw_token_commission() -> Weight {
        Weight::from_parts(102_456_000, 8_192)
            .saturating_add(RocksDbWeight::get().reads(16_u64))
            .saturating_add(RocksDbWeight::get().writes(7_u64))
    }

    fn set_token_withdrawal_config() -> Weight {
        Weight::from_parts(48_632_000, 5_120)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn set_global_min_token_repurchase_rate() -> Weight {
        Weight::from_parts(18_743_000, 2_048)
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn withdraw_entity_funds() -> Weight {
        Weight::from_parts(62_318_000, 5_120)
            .saturating_add(RocksDbWeight::get().reads(8_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }

    fn withdraw_entity_token_funds() -> Weight {
        Weight::from_parts(65_127_000, 5_120)
            .saturating_add(RocksDbWeight::get().reads(9_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }

    fn set_creator_reward_rate() -> Weight {
        Weight::from_parts(41_832_000, 4_096)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn set_token_platform_fee_rate() -> Weight {
        Weight::from_parts(16_218_000, 2_048)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn set_global_min_repurchase_rate() -> Weight {
        Weight::from_parts(18_743_000, 2_048)
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn set_withdrawal_cooldown() -> Weight {
        Weight::from_parts(39_527_000, 4_096)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn force_disable_entity_commission() -> Weight {
        Weight::from_parts(35_218_000, 3_072)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }

    fn set_global_max_commission_rate() -> Weight {
        Weight::from_parts(18_743_000, 2_048)
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn clear_commission_config() -> Weight {
        Weight::from_parts(38_124_000, 4_096)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }

    fn clear_withdrawal_config() -> Weight {
        Weight::from_parts(32_456_000, 3_584)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn clear_token_withdrawal_config() -> Weight {
        Weight::from_parts(32_456_000, 3_584)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn set_global_max_token_commission_rate() -> Weight {
        Weight::from_parts(18_743_000, 2_048)
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn force_global_pause() -> Weight {
        Weight::from_parts(14_527_000, 1_536)
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn pause_withdrawals() -> Weight {
        Weight::from_parts(28_934_000, 3_072)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn archive_order_records() -> Weight {
        Weight::from_parts(58_743_000, 6_144)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(6_u64))
    }

    fn force_enable_entity_commission() -> Weight {
        Weight::from_parts(28_934_000, 3_072)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn retry_cancel_commission() -> Weight {
        Weight::from_parts(105_218_000, 8_192)
            .saturating_add(RocksDbWeight::get().reads(10_u64))
            .saturating_add(RocksDbWeight::get().writes(10_u64))
    }

    fn set_min_withdrawal_interval() -> Weight {
        Weight::from_parts(28_934_000, 3_072)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
}
