//! Autogenerated weights for `pallet_nex_market`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-03-07
//! STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//!
//! 注意：当前值为保守估算，需在目标硬件上运行 benchmark 替换。
//! 运行命令：
//! ```bash
//! cargo build --release --features runtime-benchmarks
//! ./target/release/nexus-node benchmark pallet \
//!     --chain dev \
//!     --pallet pallet_nex_market \
//!     --extrinsic '*' \
//!     --steps 50 \
//!     --repeat 20 \
//!     --output pallets/trading/nex-market/src/weights.rs \
//!     --template .maintain/frame-weight-template.hbs
//! ```

use frame_support::weights::Weight;

pub trait WeightInfo {
    fn place_sell_order() -> Weight;
    fn place_buy_order() -> Weight;
    fn cancel_order() -> Weight;
    fn reserve_sell_order() -> Weight;
    fn accept_buy_order() -> Weight;
    fn confirm_payment() -> Weight;
    fn process_timeout() -> Weight;
    fn submit_ocw_result() -> Weight;
    fn claim_reward() -> Weight;
    fn configure_price_protection() -> Weight;
    fn set_initial_price() -> Weight;
    fn lift_circuit_breaker() -> Weight;
    fn fund_seed_account() -> Weight;
    fn seed_liquidity() -> Weight;
    fn auto_confirm_payment() -> Weight;
    fn submit_underpaid_update() -> Weight;
    fn finalize_underpaid() -> Weight;
    fn force_pause_market() -> Weight;
    fn force_resume_market() -> Weight;
    fn force_settle_trade() -> Weight;
    fn force_cancel_trade() -> Weight;
    fn dispute_trade() -> Weight;
    fn resolve_dispute() -> Weight;
    fn set_trading_fee() -> Weight;
    fn update_order_price() -> Weight;
    fn update_deposit_exchange_rate() -> Weight;
    fn seller_confirm_received() -> Weight;
    fn ban_user() -> Weight;
    fn unban_user() -> Weight;
    fn submit_counter_evidence() -> Weight;
    fn update_order_amount() -> Weight;
    fn batch_force_settle() -> Weight;
    fn batch_force_cancel() -> Weight;
}

/// Weight functions for `pallet_nex_market` on the Substrate node.
///
/// 保守估算公式:
///   ref_time ≈ 25M × reads + 50M × writes + 10M × reserve_ops
///   proof_size ≈ 3500 + 500 × storage_items_touched
pub struct SubstrateWeight<T>(core::marker::PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    // place_sell_order: 2R + 3W + 1 reserve
    fn place_sell_order() -> Weight { Weight::from_parts(50_000_000, 6_000) }
    // place_buy_order: 2R + 3W + 1 reserve
    fn place_buy_order() -> Weight { Weight::from_parts(50_000_000, 6_000) }
    // cancel_order: 2R + 3W + 1 unreserve
    fn cancel_order() -> Weight { Weight::from_parts(60_000_000, 5_000) }
    // reserve_sell_order: 4R + 5W + 2 reserve
    fn reserve_sell_order() -> Weight { Weight::from_parts(90_000_000, 8_000) }
    // accept_buy_order: 4R + 5W + 2 reserve
    fn accept_buy_order() -> Weight { Weight::from_parts(90_000_000, 8_000) }
    // confirm_payment: 2R + 2W
    fn confirm_payment() -> Weight { Weight::from_parts(50_000_000, 5_000) }
    // process_timeout: 4R + 4W + 2 unreserve
    fn process_timeout() -> Weight { Weight::from_parts(120_000_000, 10_000) }
    // submit_ocw_result: 4R + 5W + 2 transfer/unreserve
    fn submit_ocw_result() -> Weight { Weight::from_parts(100_000_000, 8_000) }
    // claim_reward: 2R + 2W + 1 transfer
    fn claim_reward() -> Weight { Weight::from_parts(100_000_000, 8_000) }
    // configure_price_protection: 1R + 1W
    fn configure_price_protection() -> Weight { Weight::from_parts(30_000_000, 4_000) }
    // set_initial_price: 1R + 1W
    fn set_initial_price() -> Weight { Weight::from_parts(40_000_000, 5_000) }
    // lift_circuit_breaker: 1R + 1W
    fn lift_circuit_breaker() -> Weight { Weight::from_parts(30_000_000, 4_000) }
    // fund_seed_account: 1R + 1W + 1 transfer
    fn fund_seed_account() -> Weight { Weight::from_parts(50_000_000, 5_000) }
    // seed_liquidity: N × (2R + 3W + 1 reserve), worst case N=20
    fn seed_liquidity() -> Weight { Weight::from_parts(200_000_000, 20_000) }
    // auto_confirm_payment: 3R + 3W
    fn auto_confirm_payment() -> Weight { Weight::from_parts(100_000_000, 8_000) }
    // submit_underpaid_update: 2R + 2W
    fn submit_underpaid_update() -> Weight { Weight::from_parts(60_000_000, 5_000) }
    // finalize_underpaid: 4R + 4W + 2 transfer/unreserve
    fn finalize_underpaid() -> Weight { Weight::from_parts(110_000_000, 8_000) }
    // force_pause_market: 0R + 1W
    fn force_pause_market() -> Weight { Weight::from_parts(30_000_000, 4_000) }
    // force_resume_market: 0R + 1W
    fn force_resume_market() -> Weight { Weight::from_parts(30_000_000, 4_000) }
    // force_settle_trade: 4R + 5W + 2 transfer/unreserve
    fn force_settle_trade() -> Weight { Weight::from_parts(120_000_000, 10_000) }
    // force_cancel_trade: 3R + 4W + 2 unreserve
    fn force_cancel_trade() -> Weight { Weight::from_parts(100_000_000, 8_000) }
    // dispute_trade: 2R + 1W
    fn dispute_trade() -> Weight { Weight::from_parts(50_000_000, 5_000) }
    // resolve_dispute: 3R + 2W + 1 transfer
    fn resolve_dispute() -> Weight { Weight::from_parts(80_000_000, 6_000) }
    // set_trading_fee: 0R + 1W
    fn set_trading_fee() -> Weight { Weight::from_parts(30_000_000, 4_000) }
    // update_order_price: 3R + 3W + possible reserve/unreserve
    fn update_order_price() -> Weight { Weight::from_parts(60_000_000, 5_000) }
    // update_deposit_exchange_rate: 0R + 1W
    fn update_deposit_exchange_rate() -> Weight { Weight::from_parts(30_000_000, 4_000) }
    // seller_confirm_received: 3R + 4W + 2 transfer/unreserve
    fn seller_confirm_received() -> Weight { Weight::from_parts(100_000_000, 8_000) }
    // ban_user: 1R + 1W + cancel orders loop
    fn ban_user() -> Weight { Weight::from_parts(30_000_000, 4_000) }
    // unban_user: 0R + 1W
    fn unban_user() -> Weight { Weight::from_parts(30_000_000, 4_000) }
    // submit_counter_evidence: 2R + 1W
    fn submit_counter_evidence() -> Weight { Weight::from_parts(50_000_000, 5_000) }
    // update_order_amount: 3R + 3W + possible reserve/unreserve
    fn update_order_amount() -> Weight { Weight::from_parts(60_000_000, 5_000) }
    // batch_force_settle: N × force_settle, worst case N=20
    fn batch_force_settle() -> Weight { Weight::from_parts(200_000_000, 20_000) }
    // batch_force_cancel: N × force_cancel, worst case N=20
    fn batch_force_cancel() -> Weight { Weight::from_parts(200_000_000, 20_000) }
}

/// 单元测试 / 开发环境用的默认权重实现
impl WeightInfo for () {
    fn place_sell_order() -> Weight { Weight::from_parts(50_000_000, 6_000) }
    fn place_buy_order() -> Weight { Weight::from_parts(50_000_000, 6_000) }
    fn cancel_order() -> Weight { Weight::from_parts(60_000_000, 5_000) }
    fn reserve_sell_order() -> Weight { Weight::from_parts(90_000_000, 8_000) }
    fn accept_buy_order() -> Weight { Weight::from_parts(90_000_000, 8_000) }
    fn confirm_payment() -> Weight { Weight::from_parts(50_000_000, 5_000) }
    fn process_timeout() -> Weight { Weight::from_parts(120_000_000, 10_000) }
    fn submit_ocw_result() -> Weight { Weight::from_parts(100_000_000, 8_000) }
    fn claim_reward() -> Weight { Weight::from_parts(100_000_000, 8_000) }
    fn configure_price_protection() -> Weight { Weight::from_parts(30_000_000, 4_000) }
    fn set_initial_price() -> Weight { Weight::from_parts(40_000_000, 5_000) }
    fn lift_circuit_breaker() -> Weight { Weight::from_parts(30_000_000, 4_000) }
    fn fund_seed_account() -> Weight { Weight::from_parts(50_000_000, 5_000) }
    fn seed_liquidity() -> Weight { Weight::from_parts(200_000_000, 20_000) }
    fn auto_confirm_payment() -> Weight { Weight::from_parts(100_000_000, 8_000) }
    fn submit_underpaid_update() -> Weight { Weight::from_parts(60_000_000, 5_000) }
    fn finalize_underpaid() -> Weight { Weight::from_parts(110_000_000, 8_000) }
    fn force_pause_market() -> Weight { Weight::from_parts(30_000_000, 4_000) }
    fn force_resume_market() -> Weight { Weight::from_parts(30_000_000, 4_000) }
    fn force_settle_trade() -> Weight { Weight::from_parts(120_000_000, 10_000) }
    fn force_cancel_trade() -> Weight { Weight::from_parts(100_000_000, 8_000) }
    fn dispute_trade() -> Weight { Weight::from_parts(50_000_000, 5_000) }
    fn resolve_dispute() -> Weight { Weight::from_parts(80_000_000, 6_000) }
    fn set_trading_fee() -> Weight { Weight::from_parts(30_000_000, 4_000) }
    fn update_order_price() -> Weight { Weight::from_parts(60_000_000, 5_000) }
    fn update_deposit_exchange_rate() -> Weight { Weight::from_parts(30_000_000, 4_000) }
    fn seller_confirm_received() -> Weight { Weight::from_parts(100_000_000, 8_000) }
    fn ban_user() -> Weight { Weight::from_parts(30_000_000, 4_000) }
    fn unban_user() -> Weight { Weight::from_parts(30_000_000, 4_000) }
    fn submit_counter_evidence() -> Weight { Weight::from_parts(50_000_000, 5_000) }
    fn update_order_amount() -> Weight { Weight::from_parts(60_000_000, 5_000) }
    fn batch_force_settle() -> Weight { Weight::from_parts(200_000_000, 20_000) }
    fn batch_force_cancel() -> Weight { Weight::from_parts(200_000_000, 20_000) }
}
