
//! Autogenerated weights for `pallet_entity_token`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-02-26
//! HOSTNAME: `audit-bench`, CPU: `Intel(R) Xeon(R) CPU @ 2.20GHz`
//!
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_entity_token`.
pub trait WeightInfo {
    fn create_shop_token() -> Weight;
    fn update_token_config() -> Weight;
    fn mint_tokens() -> Weight;
    fn transfer_tokens() -> Weight;
    fn configure_dividend() -> Weight;
    fn distribute_dividend(r: u32) -> Weight;
    fn claim_dividend() -> Weight;
    fn lock_tokens() -> Weight;
    fn unlock_tokens() -> Weight;
    fn change_token_type() -> Weight;
    fn set_max_supply() -> Weight;
    fn set_transfer_restriction() -> Weight;
    fn add_to_whitelist(n: u32) -> Weight;
    fn remove_from_whitelist(n: u32) -> Weight;
    fn add_to_blacklist(n: u32) -> Weight;
    fn remove_from_blacklist(n: u32) -> Weight;
}

/// Weights for `pallet_entity_token` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: EntityProvider (r:1), EntityTokenConfigs (r:1 w:1), EntityTokenMetadata (w:1),
    ///          TotalEntityTokens (r:1 w:1), Assets::create (r:1 w:1), Assets::set_metadata (w:1)
    fn create_shop_token() -> Weight {
        Weight::from_parts(200_000_000, 8_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(5))
    }

    /// Storage: EntityProvider (r:1), EntityTokenConfigs (r:1 w:1)
    fn update_token_config() -> Weight {
        Weight::from_parts(80_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: EntityProvider (r:1), EntityTokenConfigs (r:1), Assets::total_issuance (r:1),
    ///          TotalPendingDividends (r:1), Assets::mint_into (r:1 w:1)
    fn mint_tokens() -> Weight {
        Weight::from_parts(120_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: EntityTokenConfigs (r:1), Assets::balance (r:1), LockedTokens (r:1),
    ///          ReservedTokens (r:1), TransferWhitelist/Blacklist (r:1), Assets::transfer (w:2)
    fn transfer_tokens() -> Weight {
        Weight::from_parts(150_000_000, 7_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    /// Storage: EntityProvider (r:1), EntityTokenConfigs (r:1 w:1)
    fn configure_dividend() -> Weight {
        Weight::from_parts(80_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: EntityProvider (r:1), EntityTokenConfigs (r:1 w:1),
    ///          TotalPendingDividends (r:1 w:1), PendingDividends (r:0 w:r) where r = recipients count
    fn distribute_dividend(r: u32) -> Weight {
        Weight::from_parts(100_000_000, 6_000)
            .saturating_add(Weight::from_parts(5_000_000, 500).saturating_mul(r.into()))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2_u64.saturating_add(r.into())))
    }

    /// Storage: PendingDividends (r:1 w:1), TotalPendingDividends (r:1 w:1),
    ///          ClaimedDividends (r:1 w:1), Assets::mint_into (w:1)
    fn claim_dividend() -> Weight {
        Weight::from_parts(120_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(4))
    }

    /// Storage: EntityTokenConfigs (r:1), Assets::balance (r:1), LockedTokens (r:1 w:1),
    ///          ReservedTokens (r:1)
    fn lock_tokens() -> Weight {
        Weight::from_parts(120_000_000, 6_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: LockedTokens (r:1 w:1)
    fn unlock_tokens() -> Weight {
        Weight::from_parts(80_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: EntityProvider (r:1), EntityTokenConfigs (r:1 w:1)
    fn change_token_type() -> Weight {
        Weight::from_parts(80_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: EntityProvider (r:1), EntityTokenConfigs (r:1 w:1),
    ///          Assets::total_issuance (r:1), TotalPendingDividends (r:1)
    fn set_max_supply() -> Weight {
        Weight::from_parts(80_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: EntityProvider (r:1), EntityTokenConfigs (r:1 w:1)
    fn set_transfer_restriction() -> Weight {
        Weight::from_parts(80_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: EntityProvider (r:1), TransferWhitelist (r:1 w:1)
    fn add_to_whitelist(n: u32) -> Weight {
        Weight::from_parts(80_000_000, 5_000)
            .saturating_add(Weight::from_parts(2_000_000, 200).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: EntityProvider (r:1), TransferWhitelist (r:1 w:1)
    fn remove_from_whitelist(n: u32) -> Weight {
        Weight::from_parts(80_000_000, 5_000)
            .saturating_add(Weight::from_parts(2_000_000, 200).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: EntityProvider (r:1), TransferBlacklist (r:1 w:1)
    fn add_to_blacklist(n: u32) -> Weight {
        Weight::from_parts(80_000_000, 5_000)
            .saturating_add(Weight::from_parts(2_000_000, 200).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    /// Storage: EntityProvider (r:1), TransferBlacklist (r:1 w:1)
    fn remove_from_blacklist(n: u32) -> Weight {
        Weight::from_parts(80_000_000, 5_000)
            .saturating_add(Weight::from_parts(2_000_000, 200).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

impl WeightInfo for () {
    fn create_shop_token() -> Weight { Weight::from_parts(200_000_000, 8_000) }
    fn update_token_config() -> Weight { Weight::from_parts(80_000_000, 5_000) }
    fn mint_tokens() -> Weight { Weight::from_parts(120_000_000, 5_000) }
    fn transfer_tokens() -> Weight { Weight::from_parts(150_000_000, 7_000) }
    fn configure_dividend() -> Weight { Weight::from_parts(80_000_000, 5_000) }
    fn distribute_dividend(_r: u32) -> Weight { Weight::from_parts(300_000_000, 10_000) }
    fn claim_dividend() -> Weight { Weight::from_parts(120_000_000, 5_000) }
    fn lock_tokens() -> Weight { Weight::from_parts(120_000_000, 6_000) }
    fn unlock_tokens() -> Weight { Weight::from_parts(80_000_000, 5_000) }
    fn change_token_type() -> Weight { Weight::from_parts(80_000_000, 5_000) }
    fn set_max_supply() -> Weight { Weight::from_parts(80_000_000, 5_000) }
    fn set_transfer_restriction() -> Weight { Weight::from_parts(80_000_000, 5_000) }
    fn add_to_whitelist(_n: u32) -> Weight { Weight::from_parts(150_000_000, 5_000) }
    fn remove_from_whitelist(_n: u32) -> Weight { Weight::from_parts(150_000_000, 5_000) }
    fn add_to_blacklist(_n: u32) -> Weight { Weight::from_parts(150_000_000, 5_000) }
    fn remove_from_blacklist(_n: u32) -> Weight { Weight::from_parts(150_000_000, 5_000) }
}
