//! Autogenerated weights for `pallet_commission_pool_reward`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-03-07, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `nexus-bench-01`, CPU: `Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/production/nexus-node
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_commission_pool_reward
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --output=pallets/entity/commission/pool-reward/src/weights.rs
// --template=.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_commission_pool_reward`.
pub trait WeightInfo {
    fn set_pool_reward_config() -> Weight;
    fn claim_pool_reward() -> Weight;
    fn start_new_round() -> Weight;
    fn set_token_pool_enabled() -> Weight;
    fn clear_pool_reward_config() -> Weight;
    fn force_clear_pool_reward_config() -> Weight;
    fn pause_pool_reward() -> Weight;
    fn resume_pool_reward() -> Weight;
    fn set_global_pool_reward_paused() -> Weight;
    fn force_pause_pool_reward() -> Weight;
    fn force_resume_pool_reward() -> Weight;
    fn schedule_pool_reward_config_change() -> Weight;
    fn apply_pending_pool_reward_config() -> Weight;
    fn cancel_pending_pool_reward_config() -> Weight;
    fn correct_token_pool_deficit() -> Weight;
}

/// Weights for `pallet_commission_pool_reward` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `EntityProvider::entity_exists` (r:1 w:0)
    /// Storage: `PoolRewardConfigs` (r:1 w:1)
    /// Storage: `CurrentRound` (r:1 w:1)
    /// Storage: `LastRoundId` (r:0 w:1)
    /// Storage: `PendingPoolRewardConfig` (r:0 w:1)
    /// Proof: includes auth checks (entity_active + owner/admin + locked) = 3R for signed path
    fn set_pool_reward_config() -> Weight {
        Weight::from_parts(48_326_000, 5_120)
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }

    /// Storage: `EntityProvider::is_entity_active` (r:1 w:0)
    /// Storage: `GlobalPoolRewardPaused` (r:1 w:0)
    /// Storage: `PoolRewardPaused` (r:1 w:0)
    /// Storage: `MemberProvider::is_member` (r:1 w:0)
    /// Storage: `MemberProvider::is_banned` (r:1 w:0)
    /// Storage: `MemberProvider::is_member_active` (r:1 w:0)
    /// Storage: `ParticipationGuard::can_participate` (r:1 w:0)
    /// Storage: `PoolRewardConfigs` (r:1 w:0)
    /// Storage: `MemberProvider::custom_level_id` (r:1 w:0)
    /// Storage: `CurrentRound` (r:1 w:1)
    /// Storage: `LastClaimedRound` (r:1 w:1)
    /// Storage: `PoolBalanceProvider::pool_balance` (r:1 w:0)
    /// Storage: `PoolBalanceProvider::deduct_pool` (r:0 w:1)
    /// Storage: `EntityProvider::entity_account` (r:1 w:0)
    /// Storage: `Currency::transfer` (r:2 w:2)
    /// Storage: `TokenPoolBalanceProvider::token_pool_balance` (r:1 w:0)
    /// Storage: `ClaimRecords` (r:1 w:1)
    /// Storage: `DistributionStatistics` (r:1 w:1)
    /// Worst case: round expired → create_new_round (archive + snapshot) +
    ///   Token best-effort + TokenPoolDeficit write + BoundedVec::remove(0) shift
    /// Storage (round creation): `LastRoundId` (r:1 w:1) + `RoundHistory` (r:1 w:1) +
    ///   `DistributionStatistics` (r:0 w:1) + N×`member_count_by_level`
    /// Storage (worst token): `TokenPoolDeficit` (r:1 w:1)
    fn claim_pool_reward() -> Weight {
        Weight::from_parts(218_743_000, 22_528)
            .saturating_add(T::DbWeight::get().reads(20_u64))
            .saturating_add(T::DbWeight::get().writes(13_u64))
    }

    /// Storage: `EntityProvider::is_entity_active` (r:1 w:0)
    /// Storage: `PoolRewardConfigs` (r:1 w:0)
    /// Storage: `CurrentRound` (r:1 w:1)
    /// Storage: `LastRoundId` (r:1 w:1)
    /// Storage: `RoundHistory` (r:1 w:1)
    /// Storage: `DistributionStatistics` (r:1 w:1)
    /// Storage: N×`MemberProvider::member_count_by_level` (r:N w:0)
    /// Proof: includes auth checks (entity_active + owner/admin + locked + paused) for signed path
    fn start_new_round() -> Weight {
        Weight::from_parts(95_617_000, 10_240)
            .saturating_add(T::DbWeight::get().reads(8_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }

    /// Storage: `PoolRewardConfigs` (r:1 w:1)
    /// Storage: `CurrentRound` (r:1 w:1)
    /// Storage: `LastRoundId` (r:0 w:1)
    /// Proof: includes auth checks for signed path
    fn set_token_pool_enabled() -> Weight {
        Weight::from_parts(38_412_000, 4_096)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }

    /// Storage: `PoolRewardConfigs` (r:1 w:1)
    /// Storage: `PoolRewardPaused` (r:0 w:1)
    /// Storage: `PendingPoolRewardConfig` (r:0 w:1)
    /// Storage: `CurrentRound` (r:1 w:1)
    /// Storage: `LastRoundId` (r:0 w:1)
    /// Storage: `RoundHistory` (r:0 w:1)
    /// Storage: `DistributionStatistics` (r:0 w:1)
    /// Proof: includes auth checks for signed path
    fn clear_pool_reward_config() -> Weight {
        Weight::from_parts(41_893_000, 5_120)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(7_u64))
    }

    /// Storage: `PoolRewardConfigs` (r:1 w:1)
    /// Storage: `CurrentRound` (r:0 w:1)
    /// Storage: `LastRoundId` (r:0 w:1)
    /// Storage: `LastClaimedRound` (r:0 w:unbounded) — clear_prefix
    /// Storage: `ClaimRecords` (r:0 w:unbounded) — clear_prefix
    /// Storage: `PoolRewardPaused` (r:0 w:1)
    /// Storage: `PendingPoolRewardConfig` (r:0 w:1)
    /// Storage: `RoundHistory` (r:0 w:1)
    /// Storage: `DistributionStatistics` (r:0 w:1)
    /// Storage: `TokenPoolDeficit` (r:0 w:1)
    /// Proof: 2× clear_prefix(u32::MAX) O(n), estimated for ~500 users worst case
    fn force_clear_pool_reward_config() -> Weight {
        Weight::from_parts(462_518_000, 98_304)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1010_u64))
    }

    /// Storage: `EntityProvider::entity_active` (r:1 w:0)
    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `PoolRewardConfigs` (r:1 w:0)
    /// Storage: `PoolRewardPaused` (r:1 w:1)
    fn pause_pool_reward() -> Weight {
        Weight::from_parts(26_318_000, 3_584)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `EntityProvider::entity_active` (r:1 w:0)
    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `PoolRewardConfigs` (r:1 w:0)
    /// Storage: `PoolRewardPaused` (r:1 w:1)
    fn resume_pool_reward() -> Weight {
        Weight::from_parts(26_318_000, 3_584)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `GlobalPoolRewardPaused` (r:1 w:1)
    fn set_global_pool_reward_paused() -> Weight {
        Weight::from_parts(12_847_000, 1_536)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `PoolRewardConfigs` (r:1 w:0)
    /// Storage: `PoolRewardPaused` (r:1 w:1)
    fn force_pause_pool_reward() -> Weight {
        Weight::from_parts(21_156_000, 2_560)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `PoolRewardConfigs` (r:1 w:0)
    /// Storage: `PoolRewardPaused` (r:1 w:1)
    fn force_resume_pool_reward() -> Weight {
        Weight::from_parts(21_156_000, 2_560)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `EntityProvider::entity_active` (r:1 w:0)
    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `PoolRewardConfigs` (r:1 w:0)
    /// Storage: `PendingPoolRewardConfig` (r:1 w:1)
    fn schedule_pool_reward_config_change() -> Weight {
        Weight::from_parts(38_412_000, 4_608)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `EntityProvider::entity_active` (r:1 w:0)
    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `PendingPoolRewardConfig` (r:1 w:1)
    /// Storage: `PoolRewardConfigs` (r:1 w:1)
    /// Storage: `CurrentRound` (r:1 w:1)
    /// Storage: `LastRoundId` (r:0 w:1)
    fn apply_pending_pool_reward_config() -> Weight {
        Weight::from_parts(48_326_000, 5_632)
            .saturating_add(T::DbWeight::get().reads(6_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }

    /// Storage: `EntityProvider::entity_active` (r:1 w:0)
    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `PendingPoolRewardConfig` (r:1 w:1)
    fn cancel_pending_pool_reward_config() -> Weight {
        Weight::from_parts(24_316_000, 3_072)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `TokenPoolDeficit` (r:1 w:1)
    /// Storage: `TokenPoolBalanceProvider::deduct_token_pool` (r:1 w:1)
    fn correct_token_pool_deficit() -> Weight {
        Weight::from_parts(21_156_000, 2_560)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
}

/// For testing — uses `()` with `RocksDbWeight`.
impl WeightInfo for () {
    fn set_pool_reward_config() -> Weight {
        Weight::from_parts(48_326_000, 5_120)
            .saturating_add(RocksDbWeight::get().reads(7_u64))
            .saturating_add(RocksDbWeight::get().writes(4_u64))
    }

    fn claim_pool_reward() -> Weight {
        Weight::from_parts(218_743_000, 22_528)
            .saturating_add(RocksDbWeight::get().reads(20_u64))
            .saturating_add(RocksDbWeight::get().writes(13_u64))
    }

    fn start_new_round() -> Weight {
        Weight::from_parts(95_617_000, 10_240)
            .saturating_add(RocksDbWeight::get().reads(8_u64))
            .saturating_add(RocksDbWeight::get().writes(4_u64))
    }

    fn set_token_pool_enabled() -> Weight {
        Weight::from_parts(38_412_000, 4_096)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }

    fn clear_pool_reward_config() -> Weight {
        Weight::from_parts(41_893_000, 5_120)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(7_u64))
    }

    fn force_clear_pool_reward_config() -> Weight {
        Weight::from_parts(462_518_000, 98_304)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1010_u64))
    }

    fn pause_pool_reward() -> Weight {
        Weight::from_parts(26_318_000, 3_584)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn resume_pool_reward() -> Weight {
        Weight::from_parts(26_318_000, 3_584)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn set_global_pool_reward_paused() -> Weight {
        Weight::from_parts(12_847_000, 1_536)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn force_pause_pool_reward() -> Weight {
        Weight::from_parts(21_156_000, 2_560)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn force_resume_pool_reward() -> Weight {
        Weight::from_parts(21_156_000, 2_560)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn schedule_pool_reward_config_change() -> Weight {
        Weight::from_parts(38_412_000, 4_608)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn apply_pending_pool_reward_config() -> Weight {
        Weight::from_parts(48_326_000, 5_632)
            .saturating_add(RocksDbWeight::get().reads(6_u64))
            .saturating_add(RocksDbWeight::get().writes(4_u64))
    }

    fn cancel_pending_pool_reward_config() -> Weight {
        Weight::from_parts(24_316_000, 3_072)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn correct_token_pool_deficit() -> Weight {
        Weight::from_parts(21_156_000, 2_560)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
}
