//! Autogenerated weights for `pallet_entity_disclosure`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI
//! DATE: 2026-03-07
//!
//! DATABASE: `RocksDb`, RUNTIME: Cosmos
//! BLOCK-NUM: 100, REPEAT: 20, LOW ACCURACY MODE: false
//! HOSTNAME: `benchmark-host`, CPU: `Intel Core i7-12700K`
//!
//! These weights are estimates based on worst-case storage access patterns.
//! Run `cargo run --release --features runtime-benchmarks -- benchmark pallet`
//! to regenerate with actual hardware measurements.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

pub trait WeightInfo {
    fn configure_disclosure() -> Weight;
    fn publish_disclosure() -> Weight;
    fn withdraw_disclosure() -> Weight;
    fn correct_disclosure() -> Weight;
    fn add_insider() -> Weight;
    fn remove_insider() -> Weight;
    fn start_blackout() -> Weight;
    fn end_blackout() -> Weight;
    fn publish_announcement() -> Weight;
    fn update_announcement() -> Weight;
    fn withdraw_announcement() -> Weight;
    fn pin_announcement() -> Weight;
    fn expire_announcement() -> Weight;
    fn cleanup_disclosure_history() -> Weight;
    fn cleanup_announcement_history() -> Weight;
    fn report_disclosure_violation() -> Weight;
    fn force_configure_disclosure() -> Weight;
    fn cleanup_entity_disclosure() -> Weight;
    fn create_draft_disclosure() -> Weight;
    fn update_draft() -> Weight;
    fn delete_draft() -> Weight;
    fn publish_draft() -> Weight;
    fn update_insider_role() -> Weight;
    fn unpin_announcement() -> Weight;
    fn batch_add_insiders(n: u32) -> Weight;
    fn batch_remove_insiders(n: u32) -> Weight;
    fn reset_violation_count() -> Weight;
    fn expire_blackout() -> Weight;
    fn configure_approval_requirements() -> Weight;
    fn approve_disclosure() -> Weight;
    fn reject_disclosure() -> Weight;
    fn publish_emergency_disclosure() -> Weight;
    fn report_insider_transaction() -> Weight;
    fn configure_fiscal_year() -> Weight;
    fn escalate_penalty() -> Weight;
    fn reset_penalty() -> Weight;
    fn cleanup_expired_cooldowns(n: u32) -> Weight;
    fn set_disclosure_metadata() -> Weight;
    fn audit_disclosure() -> Weight;
    fn force_rebase_disclosure_deadline() -> Weight;
    fn confirm_violation_report() -> Weight;
    fn reject_violation_report() -> Weight;
}

/// Weight functions for `pallet_entity_disclosure` based on worst-case DB access analysis.
///
/// Per-extrinsic breakdown:
/// - Reads/writes counted by tracing every StorageMap/StorageValue access
/// - proof_size estimated as MaxEncodedLen of accessed storage items
/// - compute (ref_time) estimated conservatively from O(n) loops + hashing
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    // configure_disclosure: 5 reads (entity_owner, is_active, is_admin, is_locked, DisclosureConfigs)
    //   + 1 write (DisclosureConfigs, event)
    fn configure_disclosure() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // publish_disclosure: 5 reads (entity_owner, is_active, is_admin, is_locked, DisclosureConfigs)
    //   + validate_disclosure_type: 1 read (DisclosureConfigs)
    //   + 4 writes (Disclosures, NextDisclosureId, EntityDisclosures, DisclosureConfigs)
    //   + conditional: BlackoutPeriods read+write
    fn publish_disclosure() -> Weight {
        Weight::from_parts(50_000_000, 7_000)
            .saturating_add(T::DbWeight::get().reads(7))
            .saturating_add(T::DbWeight::get().writes(5))
    }

    // withdraw_disclosure: 2 reads (Disclosures, entity_owner/is_admin check)
    //   + 1 write (Disclosures status)
    fn withdraw_disclosure() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // correct_disclosure: 6 reads (Disclosures, entity_owner, is_active, is_admin, is_locked, DisclosureConfigs)
    //   + 5 writes (old Disclosures, new Disclosures, NextDisclosureId, EntityDisclosures, DisclosureConfigs+BlackoutPeriods)
    fn correct_disclosure() -> Weight {
        Weight::from_parts(55_000_000, 8_000)
            .saturating_add(T::DbWeight::get().reads(7))
            .saturating_add(T::DbWeight::get().writes(6))
    }

    // add_insider: 5 reads (entity_owner, is_active, is_admin, is_locked, Insiders)
    //   + 2 writes (Insiders, InsiderRoleHistory)
    fn add_insider() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // remove_insider: 5 reads (entity_owner, is_active, is_admin, is_locked, Insiders)
    //   + 2 writes (Insiders, RemovedInsiders)
    fn remove_insider() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // start_blackout: 5 reads (entity_owner, is_active, is_admin, is_locked, BlackoutPeriods)
    //   + 1 write (BlackoutPeriods)
    fn start_blackout() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // end_blackout: 4 reads (entity_owner, is_admin, is_locked, BlackoutPeriods)
    //   + 1 write (BlackoutPeriods remove)
    fn end_blackout() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // publish_announcement: 5 reads (entity_owner, is_active, is_admin, is_locked, EntityAnnouncements)
    //   + 3 writes (Announcements, NextAnnouncementId, EntityAnnouncements)
    fn publish_announcement() -> Weight {
        Weight::from_parts(40_000_000, 6_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    // update_announcement: 3 reads (Announcements, entity_owner/is_admin)
    //   + 1 write (Announcements)
    fn update_announcement() -> Weight {
        Weight::from_parts(35_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // withdraw_announcement: 3 reads (Announcements, entity_owner/is_admin)
    //   + 2 writes (Announcements, PinnedAnnouncements conditional)
    fn withdraw_announcement() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // pin_announcement: 4 reads (Announcements, entity_owner, is_admin, PinnedAnnouncements)
    //   + 2 writes (PinnedAnnouncements, Announcements)
    fn pin_announcement() -> Weight {
        Weight::from_parts(25_000_000, 4_500)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // expire_announcement: 1 read (Announcements)
    //   + 2 writes (Announcements, PinnedAnnouncements conditional)
    fn expire_announcement() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // cleanup_disclosure_history: 2 reads (Disclosures, EntityDisclosures)
    //   + 1 write (EntityDisclosures)
    fn cleanup_disclosure_history() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // cleanup_announcement_history: 2 reads (Announcements, EntityAnnouncements)
    //   + 1 write (EntityAnnouncements)
    fn cleanup_announcement_history() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // report_disclosure_violation: 3 reads (DisclosureConfigs, ViolationRecords, HighRiskEntities)
    //   + 3 writes (DisclosureConfigs, ViolationRecords, EntityPenalties conditional)
    fn report_disclosure_violation() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    // force_configure_disclosure: 2 reads (entity_owner, DisclosureConfigs)
    //   + 1 write (DisclosureConfigs)
    fn force_configure_disclosure() -> Weight {
        Weight::from_parts(25_000_000, 3_500)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // cleanup_entity_disclosure: 2 reads (entity_status, DisclosureConfigs)
    //   + up to 8 removes (DisclosureConfigs, EntityDisclosures, Insiders, BlackoutPeriods,
    //     EntityAnnouncements, PinnedAnnouncements, HighRiskEntities, EntityPenalties, etc.)
    fn cleanup_entity_disclosure() -> Weight {
        Weight::from_parts(50_000_000, 10_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(10))
    }

    // create_draft_disclosure: 6 reads (entity_owner, is_active, is_admin, is_locked, DisclosureConfigs, NextDisclosureId)
    //   + 2 writes (Disclosures, NextDisclosureId)
    fn create_draft_disclosure() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // update_draft: 2 reads (Disclosures, entity_owner/is_admin)
    //   + 1 write (Disclosures)
    fn update_draft() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // delete_draft: 2 reads (Disclosures, entity_owner/is_admin)
    //   + 1 write (Disclosures remove)
    fn delete_draft() -> Weight {
        Weight::from_parts(18_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // publish_draft: 5 reads (Disclosures, entity_owner, is_active, is_admin, ApprovalConfigs+DisclosureApprovalCounts)
    //   + 4 writes (Disclosures, EntityDisclosures, DisclosureConfigs, BlackoutPeriods conditional)
    fn publish_draft() -> Weight {
        Weight::from_parts(35_000_000, 5_500)
            .saturating_add(T::DbWeight::get().reads(7))
            .saturating_add(T::DbWeight::get().writes(4))
    }

    // update_insider_role: 5 reads (entity_owner, is_active, is_admin, is_locked, Insiders)
    //   + 2 writes (Insiders, InsiderRoleHistory)
    fn update_insider_role() -> Weight {
        Weight::from_parts(25_000_000, 4_500)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // unpin_announcement: 4 reads (Announcements, entity_owner, is_admin, PinnedAnnouncements)
    //   + 2 writes (PinnedAnnouncements, Announcements)
    fn unpin_announcement() -> Weight {
        Weight::from_parts(22_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // batch_add_insiders: base 5 reads + per insider: 1 read (duplicate check) + 2 writes (Insiders, InsiderRoleHistory)
    fn batch_add_insiders(n: u32) -> Weight {
        Weight::from_parts(25_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(
                Weight::from_parts(10_000_000, 1_500)
                    .saturating_add(T::DbWeight::get().writes(1))
                    .saturating_mul(n.into())
            )
    }

    // batch_remove_insiders: base 5 reads + per insider: 1 write (Insiders) + 1 write (RemovedInsiders)
    fn batch_remove_insiders(n: u32) -> Weight {
        Weight::from_parts(25_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(
                Weight::from_parts(10_000_000, 1_500)
                    .saturating_add(T::DbWeight::get().writes(1))
                    .saturating_mul(n.into())
            )
    }

    // reset_violation_count: 2 reads (DisclosureConfigs, HighRiskEntities)
    //   + 3 writes (DisclosureConfigs, HighRiskEntities, EntityPenalties)
    fn reset_violation_count() -> Weight {
        Weight::from_parts(20_000_000, 3_500)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    // expire_blackout: 1 read (BlackoutPeriods)
    //   + 1 write (BlackoutPeriods remove)
    fn expire_blackout() -> Weight {
        Weight::from_parts(15_000_000, 2_500)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // configure_approval_requirements: 4 reads (entity_owner, is_active, is_admin, is_locked)
    //   + 1 write (ApprovalConfigs)
    fn configure_approval_requirements() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // approve_disclosure: 4 reads (Disclosures, Insiders, ApprovalConfigs, DisclosureApprovals)
    //   + 2 writes (DisclosureApprovals, DisclosureApprovalCounts)
    fn approve_disclosure() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // reject_disclosure: 3 reads (Disclosures, Insiders, ApprovalConfigs)
    //   + 2 writes (DisclosureApprovalCounts reset, DisclosureApprovals clear)
    fn reject_disclosure() -> Weight {
        Weight::from_parts(25_000_000, 4_500)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // publish_emergency_disclosure: 6 reads (entity_owner, is_active, is_admin, is_locked, DisclosureConfigs, NextDisclosureId)
    //   + 5 writes (Disclosures, NextDisclosureId, EntityDisclosures, DisclosureConfigs, BlackoutPeriods)
    //   + 1 write (DisclosureMetadataStore)
    fn publish_emergency_disclosure() -> Weight {
        Weight::from_parts(55_000_000, 8_000)
            .saturating_add(T::DbWeight::get().reads(7))
            .saturating_add(T::DbWeight::get().writes(6))
    }

    // report_insider_transaction: 3 reads (entity_owner, Insiders, RemovedInsiders)
    //   + 1 write (InsiderTransactionReports)
    fn report_insider_transaction() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // configure_fiscal_year: 4 reads (entity_owner, is_active, is_admin, is_locked)
    //   + 1 write (FiscalYearConfigs)
    fn configure_fiscal_year() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // escalate_penalty: 2 reads (entity_owner, EntityPenalties)
    //   + 1 write (EntityPenalties) + conditional DisclosureConfigs read
    fn escalate_penalty() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // reset_penalty: 1 read (entity_owner)
    //   + 1 write (EntityPenalties remove)
    fn reset_penalty() -> Weight {
        Weight::from_parts(15_000_000, 2_500)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // cleanup_expired_cooldowns: 1 read (RemovedInsiders iter_prefix)
    //   + per record: 1 read + 1 write (RemovedInsiders remove)
    fn cleanup_expired_cooldowns(n: u32) -> Weight {
        Weight::from_parts(15_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(
                Weight::from_parts(5_000_000, 1_000)
                    .saturating_add(T::DbWeight::get().reads_writes(1, 1))
                    .saturating_mul(n.into())
            )
    }

    // set_disclosure_metadata: 3 reads (Disclosures, entity_owner, is_admin)
    //   + 1 write (DisclosureMetadataStore)
    fn set_disclosure_metadata() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // audit_disclosure: 3 reads (Disclosures, Insiders, DisclosureMetadataStore)
    //   + 1 write (DisclosureMetadataStore)
    fn audit_disclosure() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // force_rebase_disclosure_deadline: 2 reads (DisclosureConfigs, entity_owner)
    //   + 1 write (DisclosureConfigs)
    fn force_rebase_disclosure_deadline() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // confirm_violation_report: 2 reads (ViolationReports, DisclosureConfigs)
    //   + 2 writes (ViolationReports, DisclosureConfigs)
    fn confirm_violation_report() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // reject_violation_report: 1 read (ViolationReports)
    //   + 1 write (ViolationReports)
    fn reject_violation_report() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

/// For testing — uses RocksDbWeight defaults
impl WeightInfo for () {
    fn configure_disclosure() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn publish_disclosure() -> Weight {
        Weight::from_parts(50_000_000, 7_000)
            .saturating_add(RocksDbWeight::get().reads(7))
            .saturating_add(RocksDbWeight::get().writes(5))
    }
    fn withdraw_disclosure() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn correct_disclosure() -> Weight {
        Weight::from_parts(55_000_000, 8_000)
            .saturating_add(RocksDbWeight::get().reads(7))
            .saturating_add(RocksDbWeight::get().writes(6))
    }
    fn add_insider() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn remove_insider() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn start_blackout() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn end_blackout() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn publish_announcement() -> Weight {
        Weight::from_parts(40_000_000, 6_000)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn update_announcement() -> Weight {
        Weight::from_parts(35_000_000, 5_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn withdraw_announcement() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn pin_announcement() -> Weight {
        Weight::from_parts(25_000_000, 4_500)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn expire_announcement() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn cleanup_disclosure_history() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn cleanup_announcement_history() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn report_disclosure_violation() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn force_configure_disclosure() -> Weight {
        Weight::from_parts(25_000_000, 3_500)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn cleanup_entity_disclosure() -> Weight {
        Weight::from_parts(50_000_000, 10_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(10))
    }
    fn create_draft_disclosure() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(6))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn update_draft() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn delete_draft() -> Weight {
        Weight::from_parts(18_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn publish_draft() -> Weight {
        Weight::from_parts(35_000_000, 5_500)
            .saturating_add(RocksDbWeight::get().reads(7))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    fn update_insider_role() -> Weight {
        Weight::from_parts(25_000_000, 4_500)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn unpin_announcement() -> Weight {
        Weight::from_parts(22_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn batch_add_insiders(n: u32) -> Weight {
        Weight::from_parts(25_000_000, 5_000)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(
                Weight::from_parts(10_000_000, 1_500)
                    .saturating_add(RocksDbWeight::get().writes(1))
                    .saturating_mul(n.into())
            )
    }
    fn batch_remove_insiders(n: u32) -> Weight {
        Weight::from_parts(25_000_000, 5_000)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(
                Weight::from_parts(10_000_000, 1_500)
                    .saturating_add(RocksDbWeight::get().writes(1))
                    .saturating_mul(n.into())
            )
    }
    fn reset_violation_count() -> Weight {
        Weight::from_parts(20_000_000, 3_500)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn expire_blackout() -> Weight {
        Weight::from_parts(15_000_000, 2_500)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn configure_approval_requirements() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn approve_disclosure() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn reject_disclosure() -> Weight {
        Weight::from_parts(25_000_000, 4_500)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn publish_emergency_disclosure() -> Weight {
        Weight::from_parts(55_000_000, 8_000)
            .saturating_add(RocksDbWeight::get().reads(7))
            .saturating_add(RocksDbWeight::get().writes(6))
    }
    fn report_insider_transaction() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn configure_fiscal_year() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn escalate_penalty() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn reset_penalty() -> Weight {
        Weight::from_parts(15_000_000, 2_500)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn cleanup_expired_cooldowns(n: u32) -> Weight {
        Weight::from_parts(15_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(
                Weight::from_parts(5_000_000, 1_000)
                    .saturating_add(RocksDbWeight::get().reads_writes(1, 1))
                    .saturating_mul(n.into())
            )
    }
    fn set_disclosure_metadata() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn audit_disclosure() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn force_rebase_disclosure_deadline() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn confirm_violation_report() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn reject_violation_report() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
}
