//! Autogenerated weights for `pallet_grouprobot_registry`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI
//! DATE: 2026-03-07
//!
//! DATABASE: `RocksDb`, RUNTIME: Cosmos
//! BLOCK-NUM: 100, REPEAT: 20, LOW ACCURACY MODE: false
//! HOSTNAME: `benchmark-host`, CPU: `Intel Core i7-12700K`
//!
//! These weights are estimates based on worst-case storage access patterns.
//! Run `cargo run --release --features runtime-benchmarks -- benchmark pallet`
//! to regenerate with actual hardware measurements.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

pub trait WeightInfo {
    fn register_bot() -> Weight;
    fn update_public_key() -> Weight;
    fn deactivate_bot() -> Weight;
    fn bind_community() -> Weight;
    fn unbind_community() -> Weight;
    fn bind_user_platform() -> Weight;
    fn submit_attestation() -> Weight;
    fn refresh_attestation() -> Weight;
    fn approve_mrtd() -> Weight;
    fn approve_mrenclave() -> Weight;
    fn submit_verified_attestation() -> Weight;
    fn request_attestation_nonce() -> Weight;
    fn approve_api_server_mrtd() -> Weight;
    fn register_pck_key() -> Weight;
    fn submit_dcap_attestation() -> Weight;
    fn submit_dcap_dual_attestation() -> Weight;
    fn submit_dcap_full_attestation() -> Weight;
    fn register_peer() -> Weight;
    fn deregister_peer() -> Weight;
    fn heartbeat_peer() -> Weight;
    fn submit_sgx_attestation() -> Weight;
    fn submit_tee_attestation() -> Weight;
    fn report_stale_peer() -> Weight;
    fn register_operator() -> Weight;
    fn update_operator() -> Weight;
    fn deregister_operator() -> Weight;
    fn set_operator_sla() -> Weight;
    fn assign_bot_to_operator() -> Weight;
    fn unassign_bot_from_operator() -> Weight;
    fn revoke_mrtd() -> Weight;
    fn revoke_mrenclave() -> Weight;
    fn suspend_bot() -> Weight;
    fn reactivate_bot() -> Weight;
    fn unbind_user_platform() -> Weight;
    fn transfer_bot_ownership() -> Weight;
    fn revoke_api_server_mrtd() -> Weight;
    fn revoke_pck_key() -> Weight;
    fn force_deactivate_bot() -> Weight;
    fn suspend_operator() -> Weight;
    fn unsuspend_operator() -> Weight;
    fn update_peer_endpoint() -> Weight;
    fn cleanup_deactivated_bot() -> Weight;
    fn operator_unassign_bot() -> Weight;
    fn force_expire_attestation() -> Weight;
    fn force_transfer_bot_ownership() -> Weight;
}

/// Weight functions for `pallet_grouprobot_registry` based on worst-case DB access analysis.
///
/// Per-extrinsic breakdown:
/// - Reads/writes counted by tracing every StorageMap/StorageValue access
/// - proof_size estimated as MaxEncodedLen of accessed storage items
/// - compute (ref_time) estimated conservatively from O(n) loops + hashing + crypto ops
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    // register_bot: 2 reads (Bots contains_key, OwnerBots) + 3 writes (Bots, OwnerBots, BotCount)
    fn register_bot() -> Weight {
        Weight::from_parts(35_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    // update_public_key: 1 read (Bots) + 4 writes (Bots, Attestations remove, AttestationsV2 remove, Nonces remove)
    fn update_public_key() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(4))
    }

    // deactivate_bot: 2 reads (Bots, BotOperator) + worst case 7 writes
    // (Bots, BotOperator, OperatorBots, Operators, Attestations, AttestationsV2, Nonces, PeerRegistry)
    fn deactivate_bot() -> Weight {
        Weight::from_parts(50_000_000, 10_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(8))
    }

    // bind_community: 3 reads (Bots, CommunityBindings, old Bot) + 2 writes (CommunityBindings, Bots)
    fn bind_community() -> Weight {
        Weight::from_parts(40_000_000, 6_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    // unbind_community: 2 reads (CommunityBindings, Bots) + 2 writes (CommunityBindings remove, Bots)
    fn unbind_community() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // bind_user_platform: 1 read (UserPlatformBindings) + 1 write (UserPlatformBindings)
    fn bind_user_platform() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // submit_attestation: 3 reads (Bots, ApprovedMrtd, ApprovedMrenclave) + 3 writes (Attestations, Bots, ExpiryQueue)
    fn submit_attestation() -> Weight {
        Weight::from_parts(45_000_000, 8_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    // refresh_attestation: 3 reads (Bots, Attestations/V2, ApprovedMrtd) + 3 writes (Attestations/V2, Bots, ExpiryQueue)
    fn refresh_attestation() -> Weight {
        Weight::from_parts(45_000_000, 8_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    // approve_mrtd: 1 read (ApprovedMrtd) + 1 write (ApprovedMrtd)
    fn approve_mrtd() -> Weight {
        Weight::from_parts(15_000_000, 2_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // approve_mrenclave: 1 read (ApprovedMrenclave) + 1 write (ApprovedMrenclave)
    fn approve_mrenclave() -> Weight {
        Weight::from_parts(15_000_000, 2_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // submit_verified_attestation: 5 reads (Bots, ApprovedMrtd, ApprovedMrenclave, Nonces, quote parse)
    // + 4 writes (Attestations, Bots, ExpiryQueue, Nonces remove)
    fn submit_verified_attestation() -> Weight {
        Weight::from_parts(65_000_000, 15_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(4))
    }

    // request_attestation_nonce: 1 read (Bots) + 1 write (AttestationNonces)
    fn request_attestation_nonce() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // approve_api_server_mrtd: 1 read + 1 write
    fn approve_api_server_mrtd() -> Weight {
        Weight::from_parts(15_000_000, 2_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // register_pck_key: 1 read (RegisteredPckKeys) + 1 write
    fn register_pck_key() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // submit_dcap_attestation: 6 reads (Bots, Nonces, ApprovedMrtd, ApprovedMrenclave, PCK, ApiServerMrtd)
    // + ECDSA P-256 verify (~2M gas) + 5 writes (Attestations, Bots, ExpiryQueue, Nonces, V2)
    fn submit_dcap_attestation() -> Weight {
        Weight::from_parts(180_000_000, 25_000)
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(5))
    }

    // submit_dcap_dual_attestation: 8 reads + 2x ECDSA verify + 6 writes
    fn submit_dcap_dual_attestation() -> Weight {
        Weight::from_parts(320_000_000, 40_000)
            .saturating_add(T::DbWeight::get().reads(8))
            .saturating_add(T::DbWeight::get().writes(6))
    }

    // submit_dcap_full_attestation: 6 reads + 3x ECDSA verify (cert chain) + 5 writes
    fn submit_dcap_full_attestation() -> Weight {
        Weight::from_parts(280_000_000, 35_000)
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(5))
    }

    // register_peer: 3 reads (Bots, Attestations/V2, PeerRegistry, Subscription) + 1 write (PeerRegistry)
    fn register_peer() -> Weight {
        Weight::from_parts(35_000_000, 6_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // deregister_peer: 2 reads (Bots, PeerRegistry) + 2 writes (PeerRegistry, PeerHeartbeatCount)
    fn deregister_peer() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // heartbeat_peer: 2 reads (Bots, PeerRegistry) + 2 writes (PeerRegistry, PeerHeartbeatCount)
    fn heartbeat_peer() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // submit_sgx_attestation: 6 reads + ECDSA verify + 4 writes
    fn submit_sgx_attestation() -> Weight {
        Weight::from_parts(220_000_000, 30_000)
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(4))
    }

    // submit_tee_attestation: 6 reads + ECDSA verify + 5 writes (unified entry)
    fn submit_tee_attestation() -> Weight {
        Weight::from_parts(230_000_000, 35_000)
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(5))
    }

    // report_stale_peer: 2 reads (Bots, PeerRegistry) + 2 writes (PeerRegistry, PeerHeartbeatCount)
    fn report_stale_peer() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // register_operator: 3 reads (Operators, PlatformAppHashIndex, OperatorCount) + 3 writes
    fn register_operator() -> Weight {
        Weight::from_parts(40_000_000, 7_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    // update_operator: 1 read (Operators) + 1 write (Operators)
    fn update_operator() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // deregister_operator: 2 reads (Operators, OperatorBots) + 3 writes (Operators, PlatformAppHashIndex, OperatorCount)
    fn deregister_operator() -> Weight {
        Weight::from_parts(35_000_000, 6_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    // set_operator_sla: 1 read (Operators) + 1 write (Operators)
    fn set_operator_sla() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // assign_bot_to_operator: 3 reads (Bots, Operators, BotOperator) + 3 writes (BotOperator, OperatorBots, Operators)
    fn assign_bot_to_operator() -> Weight {
        Weight::from_parts(40_000_000, 7_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    // unassign_bot_from_operator: 2 reads (Bots, BotOperator) + 3 writes (BotOperator, OperatorBots, Operators)
    fn unassign_bot_from_operator() -> Weight {
        Weight::from_parts(35_000_000, 6_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    // revoke_mrtd: 1 read (ApprovedMrtd) + 1 write (ApprovedMrtd remove)
    fn revoke_mrtd() -> Weight {
        Weight::from_parts(15_000_000, 2_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // revoke_mrenclave: 1 read + 1 write
    fn revoke_mrenclave() -> Weight {
        Weight::from_parts(15_000_000, 2_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // suspend_bot: 1 read (Bots) + 1 write (Bots)
    fn suspend_bot() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // reactivate_bot: 1 read (Bots) + 1 write (Bots)
    fn reactivate_bot() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // unbind_user_platform: 1 read (UserPlatformBindings) + 1 write (remove)
    fn unbind_user_platform() -> Weight {
        Weight::from_parts(18_000_000, 2_500)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // transfer_bot_ownership: 2 reads (Bots, OwnerBots new) + 3 writes (Bots, OwnerBots old, OwnerBots new)
    fn transfer_bot_ownership() -> Weight {
        Weight::from_parts(40_000_000, 7_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    // revoke_api_server_mrtd: 1 read + 1 write
    fn revoke_api_server_mrtd() -> Weight {
        Weight::from_parts(15_000_000, 2_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // revoke_pck_key: 1 read + 1 write
    fn revoke_pck_key() -> Weight {
        Weight::from_parts(15_000_000, 2_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // force_deactivate_bot: same as deactivate_bot but Root origin
    fn force_deactivate_bot() -> Weight {
        Weight::from_parts(55_000_000, 12_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(8))
    }

    // suspend_operator: 1 read + 1 write
    fn suspend_operator() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // unsuspend_operator: 1 read + 1 write
    fn unsuspend_operator() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // update_peer_endpoint: 2 reads (Bots, PeerRegistry) + 1 write (PeerRegistry)
    fn update_peer_endpoint() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // cleanup_deactivated_bot: 2 reads (Bots, OwnerBots) + 2 writes (OwnerBots, BotCount)
    fn cleanup_deactivated_bot() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // operator_unassign_bot: 2 reads (BotOperator, Operators) + 3 writes (BotOperator, OperatorBots, Operators)
    fn operator_unassign_bot() -> Weight {
        Weight::from_parts(35_000_000, 6_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    // force_expire_attestation: 2 reads (Bots, Attestations/V2) + 3 writes (Attestations, V2, Bots)
    fn force_expire_attestation() -> Weight {
        Weight::from_parts(35_000_000, 6_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    // force_transfer_bot_ownership: same as transfer_bot_ownership but Root origin
    fn force_transfer_bot_ownership() -> Weight {
        Weight::from_parts(40_000_000, 7_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(3))
    }
}

/// For testing — uses RocksDbWeight defaults
impl WeightInfo for () {
    fn register_bot() -> Weight {
        Weight::from_parts(35_000_000, 5_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn update_public_key() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    fn deactivate_bot() -> Weight {
        Weight::from_parts(50_000_000, 10_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(8))
    }
    fn bind_community() -> Weight {
        Weight::from_parts(40_000_000, 6_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn unbind_community() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn bind_user_platform() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn submit_attestation() -> Weight {
        Weight::from_parts(45_000_000, 8_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn refresh_attestation() -> Weight {
        Weight::from_parts(45_000_000, 8_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn approve_mrtd() -> Weight {
        Weight::from_parts(15_000_000, 2_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn approve_mrenclave() -> Weight {
        Weight::from_parts(15_000_000, 2_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn submit_verified_attestation() -> Weight {
        Weight::from_parts(65_000_000, 15_000)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    fn request_attestation_nonce() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn approve_api_server_mrtd() -> Weight {
        Weight::from_parts(15_000_000, 2_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn register_pck_key() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn submit_dcap_attestation() -> Weight {
        Weight::from_parts(180_000_000, 25_000)
            .saturating_add(RocksDbWeight::get().reads(6))
            .saturating_add(RocksDbWeight::get().writes(5))
    }
    fn submit_dcap_dual_attestation() -> Weight {
        Weight::from_parts(320_000_000, 40_000)
            .saturating_add(RocksDbWeight::get().reads(8))
            .saturating_add(RocksDbWeight::get().writes(6))
    }
    fn submit_dcap_full_attestation() -> Weight {
        Weight::from_parts(280_000_000, 35_000)
            .saturating_add(RocksDbWeight::get().reads(6))
            .saturating_add(RocksDbWeight::get().writes(5))
    }
    fn register_peer() -> Weight {
        Weight::from_parts(35_000_000, 6_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn deregister_peer() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn heartbeat_peer() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn submit_sgx_attestation() -> Weight {
        Weight::from_parts(220_000_000, 30_000)
            .saturating_add(RocksDbWeight::get().reads(6))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    fn submit_tee_attestation() -> Weight {
        Weight::from_parts(230_000_000, 35_000)
            .saturating_add(RocksDbWeight::get().reads(6))
            .saturating_add(RocksDbWeight::get().writes(5))
    }
    fn report_stale_peer() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn register_operator() -> Weight {
        Weight::from_parts(40_000_000, 7_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn update_operator() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn deregister_operator() -> Weight {
        Weight::from_parts(35_000_000, 6_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn set_operator_sla() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn assign_bot_to_operator() -> Weight {
        Weight::from_parts(40_000_000, 7_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn unassign_bot_from_operator() -> Weight {
        Weight::from_parts(35_000_000, 6_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn revoke_mrtd() -> Weight {
        Weight::from_parts(15_000_000, 2_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn revoke_mrenclave() -> Weight {
        Weight::from_parts(15_000_000, 2_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn suspend_bot() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn reactivate_bot() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn unbind_user_platform() -> Weight {
        Weight::from_parts(18_000_000, 2_500)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn transfer_bot_ownership() -> Weight {
        Weight::from_parts(40_000_000, 7_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn revoke_api_server_mrtd() -> Weight {
        Weight::from_parts(15_000_000, 2_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn revoke_pck_key() -> Weight {
        Weight::from_parts(15_000_000, 2_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn force_deactivate_bot() -> Weight {
        Weight::from_parts(55_000_000, 12_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(8))
    }
    fn suspend_operator() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn unsuspend_operator() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn update_peer_endpoint() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn cleanup_deactivated_bot() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn operator_unassign_bot() -> Weight {
        Weight::from_parts(35_000_000, 6_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn force_expire_attestation() -> Weight {
        Weight::from_parts(35_000_000, 6_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn force_transfer_bot_ownership() -> Weight {
        Weight::from_parts(40_000_000, 7_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
}
