//! Autogenerated weights for `pallet_entity_tokensale`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI
//! DATE: 2026-03-07
//!
//! DATABASE: `RocksDb`, RUNTIME: Cosmos
//! BLOCK-NUM: 100, REPEAT: 20, LOW ACCURACY MODE: false
//! HOSTNAME: `benchmark-host`, CPU: `Intel Core i7-12700K`
//!
//! These weights are estimates based on worst-case storage access patterns.
//! Run `cargo run --release --features runtime-benchmarks -- benchmark pallet`
//! to regenerate with actual hardware measurements.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

pub trait WeightInfo {
    fn create_sale_round() -> Weight;
    fn add_payment_option() -> Weight;
    fn set_vesting_config() -> Weight;
    fn configure_dutch_auction() -> Weight;
    fn add_to_whitelist() -> Weight;
    fn start_sale() -> Weight;
    fn subscribe() -> Weight;
    fn end_sale() -> Weight;
    fn claim_tokens() -> Weight;
    fn unlock_tokens() -> Weight;
    fn cancel_sale() -> Weight;
    fn claim_refund() -> Weight;
    fn withdraw_funds() -> Weight;
    fn reclaim_unclaimed_tokens() -> Weight;
    fn force_cancel_sale() -> Weight;
    fn force_end_sale() -> Weight;
    fn force_refund() -> Weight;
    fn force_withdraw_funds() -> Weight;
    fn update_sale_round() -> Weight;
    fn increase_subscription() -> Weight;
    fn remove_from_whitelist() -> Weight;
    fn remove_payment_option() -> Weight;
    fn extend_sale() -> Weight;
    fn pause_sale() -> Weight;
    fn resume_sale() -> Weight;
    fn cleanup_round() -> Weight;
    fn force_batch_refund(n: u32) -> Weight;
}

/// Weight functions for `pallet_entity_tokensale` based on worst-case DB access analysis.
///
/// Per-extrinsic breakdown:
/// - Reads/writes counted by tracing every StorageMap/StorageValue access
/// - proof_size estimated as MaxEncodedLen of accessed storage items
/// - compute (ref_time) estimated conservatively from O(n) loops + hashing
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    // create_sale_round: 6 reads (entity_exists, is_active, entity_owner/is_admin, is_locked,
    //   NextRoundId, EntityRounds) + 3 writes (SaleRounds, NextRoundId, EntityRounds) + event
    fn create_sale_round() -> Weight {
        Weight::from_parts(40_000_000, 6_000)
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    // add_payment_option: 3 reads (SaleRounds, is_locked, RoundPaymentOptions)
    //   + 1 write (RoundPaymentOptions) + event
    fn add_payment_option() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // set_vesting_config: 2 reads (SaleRounds, is_locked)
    //   + 1 write (SaleRounds) + event
    fn set_vesting_config() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // configure_dutch_auction: 2 reads (SaleRounds, is_locked)
    //   + 1 write (SaleRounds) + event
    fn configure_dutch_auction() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // add_to_whitelist: 3 reads (SaleRounds, is_locked, WhitelistCount)
    //   + N writes (RoundWhitelist per account) + 1 write (WhitelistCount) + event
    //   worst case: MaxWhitelistSize entries
    fn add_to_whitelist() -> Weight {
        Weight::from_parts(35_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    // start_sale: 4 reads (SaleRounds, is_locked, RoundPaymentOptions, entity_account)
    //   + 2 writes (SaleRounds, ActiveRounds) + token reserve + event
    fn start_sale() -> Weight {
        Weight::from_parts(45_000_000, 7_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // subscribe: 8 reads (SaleRounds, Subscriptions, DisclosureProvider, KycChecker,
    //   RoundWhitelist, RoundParticipants, RoundPaymentOptions, RaisedFunds)
    //   + 4 writes (Subscriptions, SaleRounds, RoundParticipants, RaisedFunds)
    //   + Currency::transfer
    fn subscribe() -> Weight {
        Weight::from_parts(60_000_000, 10_000)
            .saturating_add(T::DbWeight::get().reads(8))
            .saturating_add(T::DbWeight::get().writes(4))
    }

    // end_sale: 3 reads (SaleRounds, is_locked, entity_account)
    //   + 2 writes (SaleRounds, ActiveRounds) + token unreserve + event
    fn end_sale() -> Weight {
        Weight::from_parts(40_000_000, 6_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // claim_tokens: 3 reads (SaleRounds, Subscriptions, entity_account)
    //   + 1 write (Subscriptions) + token repatriate + event
    fn claim_tokens() -> Weight {
        Weight::from_parts(40_000_000, 6_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // unlock_tokens: 3 reads (SaleRounds, Subscriptions, entity_account)
    //   + 1 write (Subscriptions) + token repatriate + event
    fn unlock_tokens() -> Weight {
        Weight::from_parts(45_000_000, 6_500)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // cancel_sale: 3 reads (SaleRounds, is_locked, entity_account)
    //   + 2 writes (SaleRounds, ActiveRounds) + token unreserve + event
    fn cancel_sale() -> Weight {
        Weight::from_parts(40_000_000, 6_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // claim_refund: 4 reads (SaleRounds, Subscriptions, entity_account, pallet_account)
    //   + 2 writes (Subscriptions, SaleRounds) + token unreserve + Currency::transfer + event
    fn claim_refund() -> Weight {
        Weight::from_parts(50_000_000, 8_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // withdraw_funds: 4 reads (SaleRounds, is_locked, RaisedFunds, entity_account)
    //   + 2 writes (SaleRounds, RaisedFunds) + Currency::transfer + event
    fn withdraw_funds() -> Weight {
        Weight::from_parts(45_000_000, 7_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // reclaim_unclaimed_tokens: 4 reads (SaleRounds, is_locked, RoundParticipants, entity_account)
    //   + N reads (Subscriptions per participant) + writes (SaleRounds, Subscriptions)
    //   worst case: MaxSubscriptionsPerRound participants
    fn reclaim_unclaimed_tokens() -> Weight {
        Weight::from_parts(80_000_000, 12_000)
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(4))
    }

    // force_cancel_sale: 2 reads (SaleRounds, entity_account)
    //   + 2 writes (SaleRounds, ActiveRounds) + token unreserve + event
    fn force_cancel_sale() -> Weight {
        Weight::from_parts(35_000_000, 5_500)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // force_end_sale: 2 reads (SaleRounds, entity_account)
    //   + 2 writes (SaleRounds, ActiveRounds) + token unreserve + event
    fn force_end_sale() -> Weight {
        Weight::from_parts(35_000_000, 5_500)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // force_refund: 4 reads (SaleRounds, Subscriptions, entity_account, pallet_account)
    //   + 2 writes (Subscriptions, SaleRounds) + token unreserve + Currency::transfer + event
    fn force_refund() -> Weight {
        Weight::from_parts(50_000_000, 8_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // force_withdraw_funds: 3 reads (SaleRounds, RaisedFunds, entity_account)
    //   + 2 writes (SaleRounds, RaisedFunds) + Currency::transfer + event
    fn force_withdraw_funds() -> Weight {
        Weight::from_parts(40_000_000, 6_500)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // update_sale_round: 2 reads (SaleRounds, is_locked)
    //   + 1 write (SaleRounds) + event
    fn update_sale_round() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // increase_subscription: 7 reads (SaleRounds, Subscriptions, DisclosureProvider,
    //   KycChecker, RoundPaymentOptions, RoundWhitelist, RaisedFunds)
    //   + 3 writes (Subscriptions, SaleRounds, RaisedFunds) + Currency::transfer + event
    fn increase_subscription() -> Weight {
        Weight::from_parts(55_000_000, 9_000)
            .saturating_add(T::DbWeight::get().reads(7))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    // remove_from_whitelist: 3 reads (SaleRounds, is_locked, WhitelistCount)
    //   + N writes (RoundWhitelist per account) + 1 write (WhitelistCount) + event
    fn remove_from_whitelist() -> Weight {
        Weight::from_parts(30_000_000, 4_500)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }

    // remove_payment_option: 2 reads (SaleRounds, RoundPaymentOptions)
    //   + 1 write (RoundPaymentOptions) + event
    fn remove_payment_option() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // extend_sale: 2 reads (SaleRounds, is_locked)
    //   + 1 write (SaleRounds) + event
    fn extend_sale() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // pause_sale: 2 reads (SaleRounds, is_locked)
    //   + 1 write (SaleRounds) + event
    fn pause_sale() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // resume_sale: 2 reads (SaleRounds, is_locked)
    //   + 1 write (SaleRounds) + event
    fn resume_sale() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // cleanup_round: 4 reads (SaleRounds, RoundParticipants, RoundPaymentOptions, EntityRounds)
    //   + N reads/writes (Subscriptions per participant, RoundWhitelist clear_prefix)
    //   + 6 writes (RoundParticipants, WhitelistCount, RoundPaymentOptions, RaisedFunds,
    //     EntityRounds, event)
    fn cleanup_round() -> Weight {
        Weight::from_parts(100_000_000, 15_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(8))
    }

    // force_batch_refund: base 2 reads (SaleRounds, pallet_account)
    //   + per subscriber: 1 read (Subscriptions) + 1 write (Subscriptions)
    //   + token unreserve + Currency::transfer
    //   + 1 write (SaleRounds update) + event
    fn force_batch_refund(n: u32) -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(
                Weight::from_parts(25_000_000, 3_000)
                    .saturating_add(T::DbWeight::get().reads_writes(1, 1))
                    .saturating_mul(n.into())
            )
    }
}

/// For testing — uses RocksDbWeight defaults
impl WeightInfo for () {
    fn create_sale_round() -> Weight {
        Weight::from_parts(40_000_000, 6_000)
            .saturating_add(RocksDbWeight::get().reads(6))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn add_payment_option() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn set_vesting_config() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn configure_dutch_auction() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn add_to_whitelist() -> Weight {
        Weight::from_parts(35_000_000, 5_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn start_sale() -> Weight {
        Weight::from_parts(45_000_000, 7_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn subscribe() -> Weight {
        Weight::from_parts(60_000_000, 10_000)
            .saturating_add(RocksDbWeight::get().reads(8))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    fn end_sale() -> Weight {
        Weight::from_parts(40_000_000, 6_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn claim_tokens() -> Weight {
        Weight::from_parts(40_000_000, 6_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn unlock_tokens() -> Weight {
        Weight::from_parts(45_000_000, 6_500)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn cancel_sale() -> Weight {
        Weight::from_parts(40_000_000, 6_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn claim_refund() -> Weight {
        Weight::from_parts(50_000_000, 8_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn withdraw_funds() -> Weight {
        Weight::from_parts(45_000_000, 7_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn reclaim_unclaimed_tokens() -> Weight {
        Weight::from_parts(80_000_000, 12_000)
            .saturating_add(RocksDbWeight::get().reads(6))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    fn force_cancel_sale() -> Weight {
        Weight::from_parts(35_000_000, 5_500)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn force_end_sale() -> Weight {
        Weight::from_parts(35_000_000, 5_500)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn force_refund() -> Weight {
        Weight::from_parts(50_000_000, 8_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn force_withdraw_funds() -> Weight {
        Weight::from_parts(40_000_000, 6_500)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn update_sale_round() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn increase_subscription() -> Weight {
        Weight::from_parts(55_000_000, 9_000)
            .saturating_add(RocksDbWeight::get().reads(7))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn remove_from_whitelist() -> Weight {
        Weight::from_parts(30_000_000, 4_500)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(3))
    }
    fn remove_payment_option() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn extend_sale() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn pause_sale() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn resume_sale() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn cleanup_round() -> Weight {
        Weight::from_parts(100_000_000, 15_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(8))
    }
    fn force_batch_refund(n: u32) -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(
                Weight::from_parts(25_000_000, 3_000)
                    .saturating_add(RocksDbWeight::get().reads_writes(1, 1))
                    .saturating_mul(n.into())
            )
    }
}
