use frame_support::weights::Weight;

/// Weight functions for pallet-commission-level-diff
pub trait WeightInfo {
    fn set_level_diff_config(l: u32) -> Weight;
    fn clear_level_diff_config() -> Weight;
    fn update_level_diff_config(l: u32) -> Weight;
    fn force_set_level_diff_config(l: u32) -> Weight;
    fn force_clear_level_diff_config() -> Weight;
}

/// Substrate weight estimates based on DB read/write analysis.
///
/// These are hand-estimated weights. For production, replace with benchmarked values
/// generated by `frame_benchmarking`.
pub struct SubstrateWeight<T>(core::marker::PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// set_level_diff_config: 3 reads (entity_owner, entity_active, entity_locked) + 1 write (config)
    /// + linear cost per level_rate entry for validation
    fn set_level_diff_config(l: u32) -> Weight {
        Weight::from_parts(
            35_000_000u64.saturating_add(1_000_000u64.saturating_mul(l as u64)),
            4_000u64,
        )
    }

    /// clear_level_diff_config: 3 reads + 1 read (contains_key) + 1 write (remove)
    fn clear_level_diff_config() -> Weight {
        Weight::from_parts(35_000_000, 4_000)
    }

    /// update_level_diff_config: 3 reads + 1 read (existing config) + 1 write
    fn update_level_diff_config(l: u32) -> Weight {
        Weight::from_parts(
            40_000_000u64.saturating_add(1_000_000u64.saturating_mul(l as u64)),
            4_000u64,
        )
    }

    /// force_set: 1 read (entity_exists) + 1 write (config)
    fn force_set_level_diff_config(l: u32) -> Weight {
        Weight::from_parts(
            30_000_000u64.saturating_add(1_000_000u64.saturating_mul(l as u64)),
            3_000u64,
        )
    }

    /// force_clear: 1 read (entity_exists) + 1 read (contains_key) + 1 write (remove)
    fn force_clear_level_diff_config() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }
}

impl WeightInfo for () {
    fn set_level_diff_config(l: u32) -> Weight {
        Weight::from_parts(
            35_000_000u64.saturating_add(1_000_000u64.saturating_mul(l as u64)),
            4_000u64,
        )
    }

    fn clear_level_diff_config() -> Weight {
        Weight::from_parts(35_000_000, 4_000)
    }

    fn update_level_diff_config(l: u32) -> Weight {
        Weight::from_parts(
            40_000_000u64.saturating_add(1_000_000u64.saturating_mul(l as u64)),
            4_000u64,
        )
    }

    fn force_set_level_diff_config(l: u32) -> Weight {
        Weight::from_parts(
            30_000_000u64.saturating_add(1_000_000u64.saturating_mul(l as u64)),
            3_000u64,
        )
    }

    fn force_clear_level_diff_config() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }
}
