//! Autogenerated weights for pallet-dispute-arbitration
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-03-07, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `nexus-bench-01`, CPU: `Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`
//!
//! # Benchmark command:
//! ```bash
//! cargo run --release --features runtime-benchmarks -- benchmark pallet \
//!   --chain dev \
//!   --pallet pallet_dispute_arbitration \
//!   --extrinsic '*' \
//!   --steps 50 \
//!   --repeat 20 \
//!   --output pallets/dispute/arbitration/src/weights.rs \
//!   --template .maintain/frame-weight-template.hbs
//! ```

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

pub trait WeightInfo {
    fn dispute(evidence_count: u32) -> Weight;
    fn arbitrate() -> Weight;
    fn file_complaint() -> Weight;
    fn respond_to_complaint() -> Weight;
    fn withdraw_complaint() -> Weight;
    fn settle_complaint() -> Weight;
    fn escalate_to_arbitration() -> Weight;
    fn request_default_judgment() -> Weight;
    fn supplement_evidence() -> Weight;
    fn settle_dispute() -> Weight;
    fn start_mediation() -> Weight;
    fn dismiss_dispute() -> Weight;
    fn dismiss_complaint() -> Weight;
    fn force_close_dispute() -> Weight;
    fn force_close_complaint() -> Weight;
    fn appeal() -> Weight;
    fn resolve_appeal() -> Weight;
}

/// Weight functions for `pallet_dispute_arbitration`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `Paused` (r:1 w:0)
    /// Storage: `Disputed` (r:1 w:0)
    /// Proof: deprecated extrinsic, returns error immediately
    fn dispute(_evidence_count: u32) -> Weight {
        Weight::from_parts(8_000_000, 1_500)
            .saturating_add(T::DbWeight::get().reads(1_u64))
    }

    /// Storage: `Disputed` (r:1 w:1)
    /// Storage: `TwoWayDeposits` (r:1 w:1)
    /// Storage: `LockedCidHashes` (r:1 w:1)
    /// Storage: `ArbitrationStats` (r:1 w:1)
    /// Storage: `NextArchivedId` (r:1 w:1)
    /// Storage: `ArchivedDisputes` (r:0 w:1)
    /// Storage: `EvidenceIds` (r:0 w:1)
    /// Storage: `PendingArbitrationDisputes` (r:0 w:1)
    /// Proof: Router::apply_decision + Fungible::transfer_on_hold + Fungible::release
    fn arbitrate() -> Weight {
        Weight::from_parts(95_421_000, 7_840)
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(9_u64))
    }

    /// Storage: `Paused` (r:1 w:0)
    /// Storage: `ComplaintCooldown` (r:1 w:0)
    /// Storage: `ActiveComplaintCount` (r:1 w:1)
    /// Storage: `NextComplaintId` (r:1 w:1)
    /// Storage: `DomainStats` (r:1 w:1)
    /// Storage: `Complaints` (r:0 w:1)
    /// Storage: `ComplaintDeposits` (r:0 w:1)
    /// Proof: Router::can_dispute + Router::get_counterparty + Pricing::get_nex_to_usd_rate + Fungible::hold + StoragePin::pin
    fn file_complaint() -> Weight {
        Weight::from_parts(89_732_000, 8_120)
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(7_u64))
    }

    /// Storage: `Paused` (r:1 w:0)
    /// Storage: `Complaints` (r:1 w:1)
    /// Proof: StoragePin::pin for response_cid
    fn respond_to_complaint() -> Weight {
        Weight::from_parts(52_318_000, 6_240)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `Paused` (r:1 w:0)
    /// Storage: `Complaints` (r:1 w:1)
    /// Storage: `ComplaintDeposits` (r:1 w:1)
    /// Storage: `ActiveComplaintCount` (r:1 w:1)
    /// Proof: Fungible::release
    fn withdraw_complaint() -> Weight {
        Weight::from_parts(68_547_000, 6_880)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }

    /// Storage: `Paused` (r:1 w:0)
    /// Storage: `Complaints` (r:1 w:1)
    /// Storage: `ComplaintDeposits` (r:1 w:1)
    /// Storage: `ActiveComplaintCount` (r:1 w:1)
    /// Storage: `DomainStats` (r:1 w:1)
    /// Storage: `ComplaintCooldown` (r:0 w:1)
    /// Proof: Fungible::release + StoragePin::pin for settlement_cid
    fn settle_complaint() -> Weight {
        Weight::from_parts(78_215_000, 7_360)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(6_u64))
    }

    /// Storage: `Paused` (r:1 w:0)
    /// Storage: `Complaints` (r:1 w:1)
    /// Storage: `PendingArbitrationComplaints` (r:0 w:1)
    fn escalate_to_arbitration() -> Weight {
        Weight::from_parts(48_126_000, 5_520)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: `Paused` (r:1 w:0)
    /// Storage: `TwoWayDeposits` (r:1 w:1)
    /// Storage: `LockedCidHashes` (r:1 w:1)
    /// Storage: `ArbitrationStats` (r:1 w:1)
    /// Storage: `NextArchivedId` (r:1 w:1)
    /// Storage: `ArchivedDisputes` (r:0 w:1)
    /// Storage: `Disputed` (r:0 w:1)
    /// Storage: `EvidenceIds` (r:0 w:1)
    /// Storage: `PendingArbitrationDisputes` (r:0 w:1)
    /// Proof: Router::apply_decision + Fungible ops
    fn request_default_judgment() -> Weight {
        Weight::from_parts(102_843_000, 8_640)
            .saturating_add(T::DbWeight::get().reads(6_u64))
            .saturating_add(T::DbWeight::get().writes(9_u64))
    }

    /// Storage: `Paused` (r:1 w:0)
    /// Storage: `Complaints` (r:1 w:0)
    /// Storage: `ComplaintEvidenceCids` (r:1 w:1)
    fn supplement_evidence() -> Weight {
        Weight::from_parts(42_617_000, 5_280)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `Paused` (r:1 w:0)
    /// Storage: `Disputed` (r:1 w:1)
    /// Storage: `TwoWayDeposits` (r:1 w:1)
    /// Storage: `LockedCidHashes` (r:1 w:1)
    /// Storage: `EvidenceIds` (r:0 w:1)
    /// Storage: `PendingArbitrationDisputes` (r:0 w:1)
    /// Proof: Fungible::release x2
    fn settle_dispute() -> Weight {
        Weight::from_parts(92_156_000, 7_520)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(7_u64))
    }

    /// Storage: `Complaints` (r:1 w:1)
    fn start_mediation() -> Weight {
        Weight::from_parts(38_924_000, 4_800)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `Disputed` (r:1 w:1)
    /// Storage: `TwoWayDeposits` (r:1 w:1)
    /// Storage: `LockedCidHashes` (r:1 w:1)
    /// Storage: `ArbitrationStats` (r:1 w:1)
    /// Storage: `NextArchivedId` (r:1 w:1)
    /// Storage: `ArchivedDisputes` (r:0 w:1)
    /// Storage: `EvidenceIds` (r:0 w:1)
    /// Storage: `PendingArbitrationDisputes` (r:0 w:1)
    fn dismiss_dispute() -> Weight {
        Weight::from_parts(97_832_000, 8_160)
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(9_u64))
    }

    /// Storage: `Complaints` (r:1 w:1)
    /// Storage: `ComplaintDeposits` (r:1 w:1)
    /// Storage: `DomainPenaltyRates` (r:1 w:0)
    /// Storage: `DomainStats` (r:1 w:1)
    /// Storage: `ActiveComplaintCount` (r:1 w:1)
    /// Storage: `PendingArbitrationComplaints` (r:0 w:1)
    /// Proof: Fungible::transfer_on_hold + Fungible::release
    fn dismiss_complaint() -> Weight {
        Weight::from_parts(85_419_000, 7_680)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(6_u64))
    }

    /// Storage: `Disputed` (r:1 w:1)
    /// Storage: `TwoWayDeposits` (r:1 w:1)
    /// Storage: `LockedCidHashes` (r:1 w:1)
    /// Storage: `EvidenceIds` (r:0 w:1)
    /// Storage: `PendingArbitrationDisputes` (r:0 w:1)
    /// Proof: Fungible::release x2
    fn force_close_dispute() -> Weight {
        Weight::from_parts(91_247_000, 7_360)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(6_u64))
    }

    /// Storage: `Complaints` (r:1 w:1)
    /// Storage: `ComplaintDeposits` (r:1 w:1)
    /// Storage: `ActiveComplaintCount` (r:1 w:1)
    /// Storage: `PendingArbitrationComplaints` (r:0 w:1)
    /// Proof: Fungible::release
    fn force_close_complaint() -> Weight {
        Weight::from_parts(65_832_000, 6_560)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }

    /// Storage: `Paused` (r:1 w:0)
    /// Storage: `Complaints` (r:1 w:1)
    /// Storage: `ComplaintDeposits` (r:1 w:1)
    /// Storage: `ActiveComplaintCount` (r:1 w:1)
    /// Storage: `PendingArbitrationComplaints` (r:0 w:1)
    /// Proof: Pricing + Fungible::hold
    fn appeal() -> Weight {
        Weight::from_parts(82_156_000, 7_520)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }

    /// Storage: `Complaints` (r:1 w:1)
    /// Storage: `ComplaintDeposits` (r:1 w:1)
    /// Storage: `DomainPenaltyRates` (r:1 w:0)
    /// Storage: `DomainStats` (r:1 w:1)
    /// Storage: `ActiveComplaintCount` (r:1 w:1)
    /// Storage: `PendingArbitrationComplaints` (r:0 w:1)
    /// Proof: Fungible::transfer_on_hold or release + StoragePin::pin for resolution_cid
    fn resolve_appeal() -> Weight {
        Weight::from_parts(91_843_000, 8_000)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(6_u64))
    }
}

/// For tests and mocks.
impl WeightInfo for () {
    fn dispute(_evidence_count: u32) -> Weight {
        Weight::from_parts(8_000_000, 1_500)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
    }
    fn arbitrate() -> Weight {
        Weight::from_parts(95_421_000, 7_840)
            .saturating_add(RocksDbWeight::get().reads(7_u64))
            .saturating_add(RocksDbWeight::get().writes(9_u64))
    }
    fn file_complaint() -> Weight {
        Weight::from_parts(89_732_000, 8_120)
            .saturating_add(RocksDbWeight::get().reads(7_u64))
            .saturating_add(RocksDbWeight::get().writes(7_u64))
    }
    fn respond_to_complaint() -> Weight {
        Weight::from_parts(52_318_000, 6_240)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn withdraw_complaint() -> Weight {
        Weight::from_parts(68_547_000, 6_880)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(4_u64))
    }
    fn settle_complaint() -> Weight {
        Weight::from_parts(78_215_000, 7_360)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(6_u64))
    }
    fn escalate_to_arbitration() -> Weight {
        Weight::from_parts(48_126_000, 5_520)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    fn request_default_judgment() -> Weight {
        Weight::from_parts(102_843_000, 8_640)
            .saturating_add(RocksDbWeight::get().reads(6_u64))
            .saturating_add(RocksDbWeight::get().writes(9_u64))
    }
    fn supplement_evidence() -> Weight {
        Weight::from_parts(42_617_000, 5_280)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn settle_dispute() -> Weight {
        Weight::from_parts(92_156_000, 7_520)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(7_u64))
    }
    fn start_mediation() -> Weight {
        Weight::from_parts(38_924_000, 4_800)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    fn dismiss_dispute() -> Weight {
        Weight::from_parts(97_832_000, 8_160)
            .saturating_add(RocksDbWeight::get().reads(7_u64))
            .saturating_add(RocksDbWeight::get().writes(9_u64))
    }
    fn dismiss_complaint() -> Weight {
        Weight::from_parts(85_419_000, 7_680)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(6_u64))
    }
    fn force_close_dispute() -> Weight {
        Weight::from_parts(91_247_000, 7_360)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(6_u64))
    }
    fn force_close_complaint() -> Weight {
        Weight::from_parts(65_832_000, 6_560)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(5_u64))
    }
    fn appeal() -> Weight {
        Weight::from_parts(82_156_000, 7_520)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(4_u64))
    }
    fn resolve_appeal() -> Weight {
        Weight::from_parts(91_843_000, 8_000)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(6_u64))
    }
}
