use frame_support::weights::Weight;

/// Weight functions for pallet-commission-multi-level
pub trait WeightInfo {
    fn set_multi_level_config(levels: u32) -> Weight;
    fn clear_multi_level_config() -> Weight;
    fn update_multi_level_params() -> Weight;
    fn add_tier() -> Weight;
    fn remove_tier() -> Weight;
    fn pause_multi_level() -> Weight;
    fn resume_multi_level() -> Weight;
    fn schedule_config_change(levels: u32) -> Weight;
    fn apply_pending_config() -> Weight;
    fn cancel_pending_config() -> Weight;
    // R10-#6: Root 强制暂停/恢复
    fn force_pause_multi_level() -> Weight;
    fn force_resume_multi_level() -> Weight;
    // R10-#4: 存储清理（R11-B1: member_count_hint 参数化）
    fn force_cleanup_entity(member_count_hint: u32) -> Weight;
}

/// Substrate weight estimates based on DB read/write analysis.
///
/// These are hand-estimated weights. For production, replace with benchmarked values
/// generated by `frame_benchmarking`.
pub struct SubstrateWeight<T>(core::marker::PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn set_multi_level_config(levels: u32) -> Weight {
        Weight::from_parts(
            35_000_000u64.saturating_add(2_000_000u64.saturating_mul(levels as u64)),
            3_000u64,
        )
    }

    fn clear_multi_level_config() -> Weight {
        Weight::from_parts(35_000_000, 3_000)
    }

    fn update_multi_level_params() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    fn add_tier() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    fn remove_tier() -> Weight {
        Weight::from_parts(38_000_000, 4_000)
    }

    fn pause_multi_level() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    fn resume_multi_level() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    fn schedule_config_change(levels: u32) -> Weight {
        Weight::from_parts(
            40_000_000u64.saturating_add(2_000_000u64.saturating_mul(levels as u64)),
            4_000u64,
        )
    }

    fn apply_pending_config() -> Weight {
        Weight::from_parts(45_000_000, 5_000)
    }

    fn cancel_pending_config() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    fn force_pause_multi_level() -> Weight {
        Weight::from_parts(25_000_000, 2_000)
    }

    fn force_resume_multi_level() -> Weight {
        Weight::from_parts(25_000_000, 2_000)
    }

    fn force_cleanup_entity(member_count_hint: u32) -> Weight {
        Weight::from_parts(
            50_000_000u64.saturating_add(1_000_000u64.saturating_mul(member_count_hint as u64)),
            5_000u64.saturating_add(500u64.saturating_mul(member_count_hint as u64)),
        )
    }
}

impl WeightInfo for () {
    fn set_multi_level_config(levels: u32) -> Weight {
        Weight::from_parts(
            35_000_000u64.saturating_add(2_000_000u64.saturating_mul(levels as u64)),
            3_000u64,
        )
    }

    fn clear_multi_level_config() -> Weight {
        Weight::from_parts(35_000_000, 3_000)
    }

    fn update_multi_level_params() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    fn add_tier() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    fn remove_tier() -> Weight {
        Weight::from_parts(38_000_000, 4_000)
    }

    fn pause_multi_level() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    fn resume_multi_level() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    fn schedule_config_change(levels: u32) -> Weight {
        Weight::from_parts(
            40_000_000u64.saturating_add(2_000_000u64.saturating_mul(levels as u64)),
            4_000u64,
        )
    }

    fn apply_pending_config() -> Weight {
        Weight::from_parts(45_000_000, 5_000)
    }

    fn cancel_pending_config() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    fn force_pause_multi_level() -> Weight {
        Weight::from_parts(25_000_000, 2_000)
    }

    fn force_resume_multi_level() -> Weight {
        Weight::from_parts(25_000_000, 2_000)
    }

    fn force_cleanup_entity(member_count_hint: u32) -> Weight {
        Weight::from_parts(
            50_000_000u64.saturating_add(1_000_000u64.saturating_mul(member_count_hint as u64)),
            5_000u64.saturating_add(500u64.saturating_mul(member_count_hint as u64)),
        )
    }
}
