//! Autogenerated weights for pallet-entity-shop
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-03-07
//! STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//!
//! 注意：以下为保守估计的占位权重，待实际 benchmark 运行后替换。
//! 运行命令：
//! ```bash
//! cargo bench -p pallet-entity-shop --features runtime-benchmarks
//! ```

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet-entity-shop.
pub trait WeightInfo {
    fn create_shop() -> Weight;
    fn update_shop() -> Weight;
    fn add_manager() -> Weight;
    fn remove_manager() -> Weight;
    fn fund_operating() -> Weight;
    fn pause_shop() -> Weight;
    fn resume_shop() -> Weight;
    fn set_location() -> Weight;
    fn close_shop() -> Weight;
    fn withdraw_operating_fund() -> Weight;
    fn finalize_close_shop() -> Weight;
    fn transfer_shop() -> Weight;
    fn set_primary_shop() -> Weight;
    fn force_pause_shop() -> Weight;
    fn force_close_shop() -> Weight;
    fn set_shop_type() -> Weight;
    fn cancel_close_shop() -> Weight;
    fn resign_manager() -> Weight;
    fn ban_shop() -> Weight;
    fn unban_shop() -> Weight;
}

/// 基于 RocksDB 的保守占位权重（待 benchmark 替换）
///
/// 权重估算策略：
/// - 读操作：每次 DB read ≈ 25µs = 25_000_000 pico
/// - 写操作：每次 DB write ≈ 100µs = 100_000_000 pico
/// - PoV：每个 storage item ≈ 1KB
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn create_shop() -> Weight {
        Weight::from_parts(175_000_000, 6_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(4))
    }
    fn update_shop() -> Weight {
        Weight::from_parts(125_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn add_manager() -> Weight {
        Weight::from_parts(100_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn remove_manager() -> Weight {
        Weight::from_parts(100_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn fund_operating() -> Weight {
        Weight::from_parts(150_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    fn pause_shop() -> Weight {
        Weight::from_parts(75_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn resume_shop() -> Weight {
        Weight::from_parts(100_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn set_location() -> Weight {
        Weight::from_parts(100_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn close_shop() -> Weight {
        Weight::from_parts(100_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    fn withdraw_operating_fund() -> Weight {
        Weight::from_parts(150_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    fn finalize_close_shop() -> Weight {
        Weight::from_parts(350_000_000, 15_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(12))
    }
    fn transfer_shop() -> Weight {
        Weight::from_parts(200_000_000, 7_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(4))
    }
    fn set_primary_shop() -> Weight {
        Weight::from_parts(100_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn force_pause_shop() -> Weight {
        Weight::from_parts(50_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn force_close_shop() -> Weight {
        Weight::from_parts(350_000_000, 15_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(12))
    }
    fn set_shop_type() -> Weight {
        Weight::from_parts(75_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn cancel_close_shop() -> Weight {
        Weight::from_parts(100_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    fn resign_manager() -> Weight {
        Weight::from_parts(75_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn ban_shop() -> Weight {
        Weight::from_parts(125_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(3))
    }
    fn unban_shop() -> Weight {
        Weight::from_parts(100_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(3))
    }
}

/// 用于测试的单位权重
impl WeightInfo for () {
    fn create_shop() -> Weight { Weight::from_parts(175_000_000, 6_000) }
    fn update_shop() -> Weight { Weight::from_parts(125_000_000, 5_000) }
    fn add_manager() -> Weight { Weight::from_parts(100_000_000, 4_000) }
    fn remove_manager() -> Weight { Weight::from_parts(100_000_000, 4_000) }
    fn fund_operating() -> Weight { Weight::from_parts(150_000_000, 5_000) }
    fn pause_shop() -> Weight { Weight::from_parts(75_000_000, 4_000) }
    fn resume_shop() -> Weight { Weight::from_parts(100_000_000, 4_000) }
    fn set_location() -> Weight { Weight::from_parts(100_000_000, 4_000) }
    fn close_shop() -> Weight { Weight::from_parts(100_000_000, 5_000) }
    fn withdraw_operating_fund() -> Weight { Weight::from_parts(150_000_000, 5_000) }
    fn finalize_close_shop() -> Weight { Weight::from_parts(350_000_000, 15_000) }
    fn transfer_shop() -> Weight { Weight::from_parts(200_000_000, 7_000) }
    fn set_primary_shop() -> Weight { Weight::from_parts(100_000_000, 4_000) }
    fn force_pause_shop() -> Weight { Weight::from_parts(50_000_000, 3_000) }
    fn force_close_shop() -> Weight { Weight::from_parts(350_000_000, 15_000) }
    fn set_shop_type() -> Weight { Weight::from_parts(75_000_000, 4_000) }
    fn cancel_close_shop() -> Weight { Weight::from_parts(100_000_000, 5_000) }
    fn resign_manager() -> Weight { Weight::from_parts(75_000_000, 3_000) }
    fn ban_shop() -> Weight { Weight::from_parts(125_000_000, 5_000) }
    fn unban_shop() -> Weight { Weight::from_parts(100_000_000, 4_000) }
}
