//! Autogenerated weights for `pallet_entity_market`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI
//! DATE: 2026-03-07
//!
//! DATABASE: `RocksDb`, RUNTIME: Cosmos
//! BLOCK-NUM: 100, REPEAT: 20, LOW ACCURACY MODE: false
//! HOSTNAME: `benchmark-host`, CPU: `Intel Core i7-12700K`
//!
//! These weights are estimates based on worst-case storage access patterns.
//! Run `cargo run --release --features runtime-benchmarks -- benchmark pallet`
//! to regenerate with actual hardware measurements.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

pub trait WeightInfo {
    fn place_sell_order() -> Weight;
    fn place_buy_order() -> Weight;
    fn take_order() -> Weight;
    fn cancel_order() -> Weight;
    fn configure_market() -> Weight;
    fn configure_price_protection() -> Weight;
    fn lift_circuit_breaker() -> Weight;
    fn set_initial_price() -> Weight;
    fn market_buy() -> Weight;
    fn market_sell() -> Weight;
    fn force_cancel_order() -> Weight;
    fn pause_market() -> Weight;
    fn resume_market() -> Weight;
    fn batch_cancel_orders(n: u32) -> Weight;
    fn cleanup_expired_orders() -> Weight;
    fn modify_order() -> Weight;
    fn global_market_pause() -> Weight;
    fn set_kyc_requirement() -> Weight;
    fn close_market() -> Weight;
    fn cancel_all_entity_orders() -> Weight;
    fn governance_configure_market() -> Weight;
    fn force_close_market() -> Weight;
    fn place_ioc_order() -> Weight;
    fn place_fok_order() -> Weight;
    fn place_post_only_order() -> Weight;
    fn governance_configure_price_protection() -> Weight;
    fn force_lift_circuit_breaker() -> Weight;
}

/// Weight functions for `pallet_entity_market` based on worst-case DB access analysis.
///
/// Per-extrinsic breakdown:
/// - Reads/writes counted by tracing every StorageMap/StorageValue access
/// - proof_size estimated as MaxEncodedLen of accessed storage items
/// - compute (ref_time) estimated conservatively from O(n) loops + hashing
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    // place_sell_order: 8 reads (GlobalMarketPaused, entity_exists, is_active, is_token_enabled,
    //   MarketStatus, MarketConfigs, KYC, DisclosureProvider, PriceProtection, TwapAccumulators,
    //   token_balance) + cross-match loop (worst case ~10 orders)
    //   + 6 writes (Orders, NextOrderId, EntitySellOrders, UserOrders, token reserve, BestAsk/BestBid)
    fn place_sell_order() -> Weight {
        Weight::from_parts(55_000_000, 8_000)
            .saturating_add(T::DbWeight::get().reads(12))
            .saturating_add(T::DbWeight::get().writes(8))
    }

    // place_buy_order: same validation as sell + NEX reserve + cross-match
    fn place_buy_order() -> Weight {
        Weight::from_parts(55_000_000, 8_000)
            .saturating_add(T::DbWeight::get().reads(12))
            .saturating_add(T::DbWeight::get().writes(8))
    }

    // take_order: 8 reads (Orders, GlobalMarketPaused, entity_exists, is_active, is_token_enabled,
    //   MarketStatus, MarketConfigs, KYC, DisclosureProvider, PriceProtection)
    //   + 8 writes (Orders, EntitySellOrders/BuyOrders, UserOrders, UserOrderHistory,
    //     MarketStats, GlobalStats, EntityDailyStats, TradeRecords, NextTradeId,
    //     UserTradeHistory×2, EntityTradeHistory, TwapAccumulators, BestAsk/BestBid)
    fn take_order() -> Weight {
        Weight::from_parts(85_000_000, 12_000)
            .saturating_add(T::DbWeight::get().reads(12))
            .saturating_add(T::DbWeight::get().writes(14))
    }

    // cancel_order: 2 reads (Orders, UserOrders) + 5 writes (Orders, EntitySellOrders/BuyOrders,
    //   UserOrders, UserOrderHistory, BestAsk/BestBid, token unreserve)
    fn cancel_order() -> Weight {
        Weight::from_parts(40_000_000, 6_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(5))
    }

    // configure_market: 5 reads (entity_exists, entity_owner, is_locked, MarketStatus, MarketConfigs)
    //   + 1 write (MarketConfigs) + conditional do_cancel_all_entity_orders
    fn configure_market() -> Weight {
        Weight::from_parts(30_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // configure_price_protection: 3 reads (entity_owner, is_locked, PriceProtection)
    //   + 1 write (PriceProtection)
    fn configure_price_protection() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // lift_circuit_breaker: 3 reads (entity_owner, is_locked, PriceProtection)
    //   + 1 write (PriceProtection)
    fn lift_circuit_breaker() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // set_initial_price: 4 reads (entity_owner, is_locked, TwapAccumulators, PriceProtection)
    //   + 2 writes (PriceProtection, TwapAccumulators)
    fn set_initial_price() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // market_buy: 10 reads (market validation + PriceProtection + EntitySellOrders + Orders loop)
    //   + 10 writes (Orders updates, transfers, stats, TWAP, BestAsk/BestBid)
    fn market_buy() -> Weight {
        Weight::from_parts(120_000_000, 15_000)
            .saturating_add(T::DbWeight::get().reads(15))
            .saturating_add(T::DbWeight::get().writes(12))
    }

    // market_sell: same complexity as market_buy
    fn market_sell() -> Weight {
        Weight::from_parts(120_000_000, 15_000)
            .saturating_add(T::DbWeight::get().reads(15))
            .saturating_add(T::DbWeight::get().writes(12))
    }

    // force_cancel_order: 1 read (Orders) + 5 writes (Orders, order book, UserOrders, history, BestAsk/BestBid)
    fn force_cancel_order() -> Weight {
        Weight::from_parts(40_000_000, 6_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(5))
    }

    // pause_market: 4 reads (entity_exists, entity_owner, is_locked, MarketConfigs)
    //   + 1 write (MarketConfigs)
    fn pause_market() -> Weight {
        Weight::from_parts(18_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // resume_market: same as pause_market
    fn resume_market() -> Weight {
        Weight::from_parts(18_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // batch_cancel_orders: base + per order (read Order + write Order + remove from book + history)
    fn batch_cancel_orders(n: u32) -> Weight {
        Weight::from_parts(15_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(
                Weight::from_parts(30_000_000, 4_000)
                    .saturating_add(T::DbWeight::get().reads_writes(1, 4))
                    .saturating_mul(n.into())
            )
    }

    // cleanup_expired_orders: 2 reads (EntitySellOrders, EntityBuyOrders) + per order cleanup
    fn cleanup_expired_orders() -> Weight {
        Weight::from_parts(80_000_000, 12_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(8))
    }

    // modify_order: 5 reads (Orders, market validation, PriceProtection)
    //   + 3 writes (Orders, reserve adjustments, BestAsk/BestBid)
    fn modify_order() -> Weight {
        Weight::from_parts(50_000_000, 7_000)
            .saturating_add(T::DbWeight::get().reads(8))
            .saturating_add(T::DbWeight::get().writes(4))
    }

    // global_market_pause: 0 reads + 1 write (GlobalMarketPaused)
    fn global_market_pause() -> Weight {
        Weight::from_parts(10_000_000, 1_500)
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // set_kyc_requirement: 4 reads (entity_exists, entity_owner, is_locked)
    //   + 1 write (MarketKycRequirement)
    fn set_kyc_requirement() -> Weight {
        Weight::from_parts(18_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // close_market: 5 reads (entity_exists, entity_owner, is_locked, MarketStatus, order books)
    //   + N writes (cancel all orders) + 1 write (MarketStatus)
    //   worst case: 2000 orders (1000 sell + 1000 buy)
    fn close_market() -> Weight {
        Weight::from_parts(500_000_000, 60_000)
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(2004))
    }

    // cancel_all_entity_orders: 2 reads (entity_exists, UserOrders) + per order cancel
    fn cancel_all_entity_orders() -> Weight {
        Weight::from_parts(200_000_000, 25_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(200))
    }

    // governance_configure_market: 3 reads (entity_exists, MarketStatus, MarketConfigs)
    //   + 1 write (MarketConfigs) + conditional cancel all
    fn governance_configure_market() -> Weight {
        Weight::from_parts(30_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // force_close_market: same as close_market but Root origin
    fn force_close_market() -> Weight {
        Weight::from_parts(500_000_000, 60_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2004))
    }

    // place_ioc_order: same validation as limit + cross-match + cancel remainder
    fn place_ioc_order() -> Weight {
        Weight::from_parts(80_000_000, 10_000)
            .saturating_add(T::DbWeight::get().reads(12))
            .saturating_add(T::DbWeight::get().writes(10))
    }

    // place_fok_order: same as IOC + pre-check fillable amount
    fn place_fok_order() -> Weight {
        Weight::from_parts(85_000_000, 10_000)
            .saturating_add(T::DbWeight::get().reads(14))
            .saturating_add(T::DbWeight::get().writes(10))
    }

    // place_post_only_order: validation + best price check + create order
    fn place_post_only_order() -> Weight {
        Weight::from_parts(50_000_000, 7_000)
            .saturating_add(T::DbWeight::get().reads(12))
            .saturating_add(T::DbWeight::get().writes(6))
    }

    // governance_configure_price_protection: 2 reads (entity_exists, PriceProtection)
    //   + 1 write (PriceProtection)
    fn governance_configure_price_protection() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // force_lift_circuit_breaker: 2 reads (entity_exists, PriceProtection)
    //   + 1 write (PriceProtection)
    fn force_lift_circuit_breaker() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

/// For testing — uses RocksDbWeight defaults
impl WeightInfo for () {
    fn place_sell_order() -> Weight {
        Weight::from_parts(55_000_000, 8_000)
            .saturating_add(RocksDbWeight::get().reads(12))
            .saturating_add(RocksDbWeight::get().writes(8))
    }
    fn place_buy_order() -> Weight {
        Weight::from_parts(55_000_000, 8_000)
            .saturating_add(RocksDbWeight::get().reads(12))
            .saturating_add(RocksDbWeight::get().writes(8))
    }
    fn take_order() -> Weight {
        Weight::from_parts(85_000_000, 12_000)
            .saturating_add(RocksDbWeight::get().reads(12))
            .saturating_add(RocksDbWeight::get().writes(14))
    }
    fn cancel_order() -> Weight {
        Weight::from_parts(40_000_000, 6_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(5))
    }
    fn configure_market() -> Weight {
        Weight::from_parts(30_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn configure_price_protection() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn lift_circuit_breaker() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn set_initial_price() -> Weight {
        Weight::from_parts(30_000_000, 5_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn market_buy() -> Weight {
        Weight::from_parts(120_000_000, 15_000)
            .saturating_add(RocksDbWeight::get().reads(15))
            .saturating_add(RocksDbWeight::get().writes(12))
    }
    fn market_sell() -> Weight {
        Weight::from_parts(120_000_000, 15_000)
            .saturating_add(RocksDbWeight::get().reads(15))
            .saturating_add(RocksDbWeight::get().writes(12))
    }
    fn force_cancel_order() -> Weight {
        Weight::from_parts(40_000_000, 6_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(5))
    }
    fn pause_market() -> Weight {
        Weight::from_parts(18_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn resume_market() -> Weight {
        Weight::from_parts(18_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn batch_cancel_orders(n: u32) -> Weight {
        Weight::from_parts(15_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(
                Weight::from_parts(30_000_000, 4_000)
                    .saturating_add(RocksDbWeight::get().reads_writes(1, 4))
                    .saturating_mul(n.into())
            )
    }
    fn cleanup_expired_orders() -> Weight {
        Weight::from_parts(80_000_000, 12_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(8))
    }
    fn modify_order() -> Weight {
        Weight::from_parts(50_000_000, 7_000)
            .saturating_add(RocksDbWeight::get().reads(8))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    fn global_market_pause() -> Weight {
        Weight::from_parts(10_000_000, 1_500)
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn set_kyc_requirement() -> Weight {
        Weight::from_parts(18_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn close_market() -> Weight {
        Weight::from_parts(500_000_000, 60_000)
            .saturating_add(RocksDbWeight::get().reads(6))
            .saturating_add(RocksDbWeight::get().writes(2004))
    }
    fn cancel_all_entity_orders() -> Weight {
        Weight::from_parts(200_000_000, 25_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(200))
    }
    fn governance_configure_market() -> Weight {
        Weight::from_parts(30_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn force_close_market() -> Weight {
        Weight::from_parts(500_000_000, 60_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2004))
    }
    fn place_ioc_order() -> Weight {
        Weight::from_parts(80_000_000, 10_000)
            .saturating_add(RocksDbWeight::get().reads(12))
            .saturating_add(RocksDbWeight::get().writes(10))
    }
    fn place_fok_order() -> Weight {
        Weight::from_parts(85_000_000, 10_000)
            .saturating_add(RocksDbWeight::get().reads(14))
            .saturating_add(RocksDbWeight::get().writes(10))
    }
    fn place_post_only_order() -> Weight {
        Weight::from_parts(50_000_000, 7_000)
            .saturating_add(RocksDbWeight::get().reads(12))
            .saturating_add(RocksDbWeight::get().writes(6))
    }
    fn governance_configure_price_protection() -> Weight {
        Weight::from_parts(25_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn force_lift_circuit_breaker() -> Weight {
        Weight::from_parts(22_000_000, 3_500)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
}
