use frame_support::weights::Weight;

/// Weight functions for pallet-commission-referral
pub trait WeightInfo {
    fn set_direct_reward_config() -> Weight;
    fn set_fixed_amount_config() -> Weight;
    fn set_first_order_config() -> Weight;
    fn set_repeat_purchase_config() -> Weight;
    fn clear_referral_config() -> Weight;
    fn force_set_direct_reward_config() -> Weight;
    fn force_set_fixed_amount_config() -> Weight;
    fn force_set_first_order_config() -> Weight;
    fn force_set_repeat_purchase_config() -> Weight;
    fn force_clear_referral_config() -> Weight;
    fn set_referrer_guard_config() -> Weight;
    fn set_commission_cap_config() -> Weight;
    fn set_referral_validity_config() -> Weight;
    fn set_config_effective_after() -> Weight;
}

/// Substrate weight estimates based on DB read/write analysis.
///
/// These are hand-estimated weights. For production, replace with benchmarked values
/// generated by `frame_benchmarking`.
pub struct SubstrateWeight<T>(core::marker::PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// 3 reads (entity_owner, entity_locked, entity_active) + 1 read/write (config mutate)
    fn set_direct_reward_config() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    fn set_fixed_amount_config() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    fn set_first_order_config() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    fn set_repeat_purchase_config() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    /// 3 reads + 1 read (contains_key) + 6 writes (do_clear_all_config)
    fn clear_referral_config() -> Weight {
        Weight::from_parts(50_000_000, 5_000)
    }

    /// Root: 1 read/write (config mutate)
    fn force_set_direct_reward_config() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    fn force_set_fixed_amount_config() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    fn force_set_first_order_config() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    fn force_set_repeat_purchase_config() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    /// Root: 1 read (contains_key) + 6 writes (do_clear_all_config)
    fn force_clear_referral_config() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    /// 3 reads + 1 write (guard config insert)
    fn set_referrer_guard_config() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    /// 3 reads + 1 write (cap config insert)
    fn set_commission_cap_config() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    /// 3 reads + 1 write (validity config insert)
    fn set_referral_validity_config() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    /// 3 reads + 1 write (effective_after insert)
    fn set_config_effective_after() -> Weight {
        Weight::from_parts(35_000_000, 4_000)
    }
}

impl WeightInfo for () {
    fn set_direct_reward_config() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    fn set_fixed_amount_config() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    fn set_first_order_config() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    fn set_repeat_purchase_config() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    fn clear_referral_config() -> Weight {
        Weight::from_parts(50_000_000, 5_000)
    }

    fn force_set_direct_reward_config() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    fn force_set_fixed_amount_config() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    fn force_set_first_order_config() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    fn force_set_repeat_purchase_config() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    fn force_clear_referral_config() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    fn set_referrer_guard_config() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    fn set_commission_cap_config() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    fn set_referral_validity_config() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    fn set_config_effective_after() -> Weight {
        Weight::from_parts(35_000_000, 4_000)
    }
}
