use frame_support::weights::Weight;

/// Weight functions for pallet-commission-team
pub trait WeightInfo {
    fn set_team_performance_config(t: u32) -> Weight;
    fn clear_team_performance_config() -> Weight;
    fn update_team_performance_params() -> Weight;
    fn force_set_team_performance_config(t: u32) -> Weight;
    fn force_clear_team_performance_config() -> Weight;
    fn pause_team_performance() -> Weight;
    fn resume_team_performance() -> Weight;
    fn add_tier() -> Weight;
    fn update_tier() -> Weight;
    fn remove_tier() -> Weight;
}

/// Substrate weight estimates based on DB read/write analysis.
///
/// These are hand-estimated weights. For production, replace with benchmarked values
/// generated by `frame_benchmarking`.
pub struct SubstrateWeight<T>(core::marker::PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// set_team_performance_config:
    /// 3 reads (entity_owner, entity_active, entity_locked) + validation per tier + 2 writes (config + enabled)
    fn set_team_performance_config(t: u32) -> Weight {
        Weight::from_parts(
            40_000_000u64.saturating_add(1_500_000u64.saturating_mul(t as u64)),
            4_000u64,
        )
    }

    /// clear_team_performance_config:
    /// 3 reads + 1 read (contains_key) + 2 writes (remove config + remove enabled)
    fn clear_team_performance_config() -> Weight {
        Weight::from_parts(35_000_000, 4_000)
    }

    /// update_team_performance_params:
    /// 3 reads + 1 read/write (try_mutate config)
    fn update_team_performance_params() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    /// force_set: validation per tier + 2 writes (config + enabled)
    fn force_set_team_performance_config(t: u32) -> Weight {
        Weight::from_parts(
            30_000_000u64.saturating_add(1_500_000u64.saturating_mul(t as u64)),
            3_000u64,
        )
    }

    /// force_clear: 1 read (contains_key) + 2 writes (remove config + remove enabled)
    fn force_clear_team_performance_config() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    /// pause: 3 reads + 1 read (contains_key) + 1 read (enabled) + 1 write (enabled)
    fn pause_team_performance() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    /// resume: 3 reads + 1 read (contains_key) + 1 read (enabled) + 1 write (enabled)
    fn resume_team_performance() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    /// add_tier: 3 reads + 1 read/write (try_mutate config) + rate validation
    fn add_tier() -> Weight {
        Weight::from_parts(45_000_000, 4_000)
    }

    /// update_tier: 3 reads + 1 read/write (try_mutate config) + ascending re-validation
    fn update_tier() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    /// remove_tier: 3 reads + 1 read/write (try_mutate config)
    fn remove_tier() -> Weight {
        Weight::from_parts(35_000_000, 4_000)
    }
}

impl WeightInfo for () {
    fn set_team_performance_config(t: u32) -> Weight {
        Weight::from_parts(
            40_000_000u64.saturating_add(1_500_000u64.saturating_mul(t as u64)),
            4_000u64,
        )
    }

    fn clear_team_performance_config() -> Weight {
        Weight::from_parts(35_000_000, 4_000)
    }

    fn update_team_performance_params() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    fn force_set_team_performance_config(t: u32) -> Weight {
        Weight::from_parts(
            30_000_000u64.saturating_add(1_500_000u64.saturating_mul(t as u64)),
            3_000u64,
        )
    }

    fn force_clear_team_performance_config() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    fn pause_team_performance() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    fn resume_team_performance() -> Weight {
        Weight::from_parts(30_000_000, 3_000)
    }

    fn add_tier() -> Weight {
        Weight::from_parts(45_000_000, 4_000)
    }

    fn update_tier() -> Weight {
        Weight::from_parts(40_000_000, 4_000)
    }

    fn remove_tier() -> Weight {
        Weight::from_parts(35_000_000, 4_000)
    }
}
