//! Autogenerated weights for pallet-entity-loyalty
//!
//! 注意：以下为保守估计的占位权重，待实际 benchmark 运行后替换。

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet-entity-loyalty.
pub trait WeightInfo {
    fn enable_points() -> Weight;
    fn disable_points() -> Weight;
    fn update_points_config() -> Weight;
    fn transfer_points() -> Weight;
    fn manager_issue_points() -> Weight;
    fn manager_burn_points() -> Weight;
    fn redeem_points() -> Weight;
    fn set_points_ttl() -> Weight;
    fn expire_points() -> Weight;
    fn set_points_max_supply() -> Weight;
}

/// 基于 RocksDB 的保守占位权重
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn enable_points() -> Weight {
        Weight::from_parts(100_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn disable_points() -> Weight {
        Weight::from_parts(200_000_000, 10_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(6))
    }
    fn update_points_config() -> Weight {
        Weight::from_parts(100_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn transfer_points() -> Weight {
        Weight::from_parts(125_000_000, 6_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(3))
    }
    fn manager_issue_points() -> Weight {
        Weight::from_parts(100_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }
    fn manager_burn_points() -> Weight {
        Weight::from_parts(100_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    fn redeem_points() -> Weight {
        Weight::from_parts(175_000_000, 7_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(3))
    }
    fn set_points_ttl() -> Weight {
        Weight::from_parts(75_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn expire_points() -> Weight {
        Weight::from_parts(100_000_000, 5_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(3))
    }
    fn set_points_max_supply() -> Weight {
        Weight::from_parts(75_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

/// 用于测试的单位权重
impl WeightInfo for () {
    fn enable_points() -> Weight { Weight::from_parts(100_000_000, 4_000) }
    fn disable_points() -> Weight { Weight::from_parts(200_000_000, 10_000) }
    fn update_points_config() -> Weight { Weight::from_parts(100_000_000, 4_000) }
    fn transfer_points() -> Weight { Weight::from_parts(125_000_000, 6_000) }
    fn manager_issue_points() -> Weight { Weight::from_parts(100_000_000, 5_000) }
    fn manager_burn_points() -> Weight { Weight::from_parts(100_000_000, 5_000) }
    fn redeem_points() -> Weight { Weight::from_parts(175_000_000, 7_000) }
    fn set_points_ttl() -> Weight { Weight::from_parts(75_000_000, 4_000) }
    fn expire_points() -> Weight { Weight::from_parts(100_000_000, 5_000) }
    fn set_points_max_supply() -> Weight { Weight::from_parts(75_000_000, 4_000) }
}
