//! Autogenerated weights for `pallet_commission_single_line`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-03-07, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `nexus-bench-01`, CPU: `Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/production/nexus-node
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_commission_single_line
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --output=pallets/entity/commission/single-line/src/weights.rs
// --template=.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_commission_single_line`.
pub trait WeightInfo {
    fn set_single_line_config() -> Weight;
    fn clear_single_line_config() -> Weight;
    fn update_single_line_params() -> Weight;
    fn set_level_based_levels() -> Weight;
    fn remove_level_based_levels() -> Weight;
    fn force_set_single_line_config() -> Weight;
    fn force_clear_single_line_config() -> Weight;
    fn force_reset_single_line(limit: u32) -> Weight;
    fn pause_single_line() -> Weight;
    fn resume_single_line() -> Weight;
    fn schedule_config_change() -> Weight;
    fn apply_pending_config() -> Weight;
    fn cancel_pending_config() -> Weight;
    fn force_remove_from_single_line() -> Weight;
}

/// Weights for `pallet_commission_single_line` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_active` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `SingleLineConfigs` (r:0 w:1)
    /// Storage: `ConfigChangeLogCount` (r:1 w:1)
    /// Storage: `ConfigChangeLogs` (r:0 w:1)
    fn set_single_line_config() -> Weight {
        Weight::from_parts(38_741_000, 4_096)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_active` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `SingleLineConfigs` (r:1 w:1)
    /// Storage: `SingleLineCustomLevelOverrides` (r:0 w:unbounded)
    fn clear_single_line_config() -> Weight {
        Weight::from_parts(35_218_000, 4_096)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_active` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `SingleLineConfigs` (r:1 w:1)
    /// Storage: `ConfigChangeLogCount` (r:1 w:1)
    /// Storage: `ConfigChangeLogs` (r:0 w:1)
    fn update_single_line_params() -> Weight {
        Weight::from_parts(41_523_000, 4_096)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_active` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `SingleLineConfigs` (r:1 w:0)
    /// Storage: `SingleLineCustomLevelOverrides` (r:0 w:1)
    fn set_level_based_levels() -> Weight {
        Weight::from_parts(28_934_000, 3_584)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_active` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `SingleLineCustomLevelOverrides` (r:1 w:1)
    fn remove_level_based_levels() -> Weight {
        Weight::from_parts(25_107_000, 3_584)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `SingleLineConfigs` (r:0 w:1)
    /// Storage: `ConfigChangeLogCount` (r:1 w:1)
    /// Storage: `ConfigChangeLogs` (r:0 w:1)
    fn force_set_single_line_config() -> Weight {
        Weight::from_parts(22_156_000, 3_072)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }

    /// Storage: `SingleLineConfigs` (r:1 w:1)
    /// Storage: `SingleLineCustomLevelOverrides` (r:0 w:unbounded)
    fn force_clear_single_line_config() -> Weight {
        Weight::from_parts(19_843_000, 3_072)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: `SingleLineSegmentCount` (r:1 w:1)
    /// Storage: `SingleLineSegments` (r:s w:s)
    /// Storage: `SingleLineIndex` (r:0 w:s*MaxSingleLineLength)
    ///
    /// The variable `s` represents the number of segments processed (capped by `limit`).
    fn force_reset_single_line(s: u32) -> Weight {
        Weight::from_parts(18_247_000, 3_584)
            // Standard cost per segment
            .saturating_add(Weight::from_parts(12_831_000_u64.saturating_mul(s as u64), 0))
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().reads(s as u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
            .saturating_add(T::DbWeight::get().writes(s as u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_active` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `SingleLineEnabled` (r:1 w:1)
    fn pause_single_line() -> Weight {
        Weight::from_parts(21_432_000, 3_072)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_active` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `SingleLineEnabled` (r:1 w:1)
    fn resume_single_line() -> Weight {
        Weight::from_parts(21_432_000, 3_072)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_active` (r:1 w:0)
    /// Storage: `EntityProvider::is_entity_locked` (r:1 w:0)
    /// Storage: `PendingConfigChanges` (r:1 w:1)
    fn schedule_config_change() -> Weight {
        Weight::from_parts(36_218_000, 4_096)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `PendingConfigChanges` (r:1 w:1)
    /// Storage: `SingleLineConfigs` (r:0 w:1)
    /// Storage: `ConfigChangeLogCount` (r:1 w:1)
    /// Storage: `ConfigChangeLogs` (r:0 w:1)
    fn apply_pending_config() -> Weight {
        Weight::from_parts(42_617_000, 4_608)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }

    /// Storage: `EntityProvider::entity_owner` (r:1 w:0)
    /// Storage: `PendingConfigChanges` (r:1 w:1)
    fn cancel_pending_config() -> Weight {
        Weight::from_parts(24_316_000, 3_072)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: `SingleLineIndex` (r:1 w:0)
    /// Storage: `RemovedMembers` (r:0 w:1)
    fn force_remove_from_single_line() -> Weight {
        Weight::from_parts(16_892_000, 2_560)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
}

/// For testing — uses `()` with `RocksDbWeight`.
impl WeightInfo for () {
    fn set_single_line_config() -> Weight {
        Weight::from_parts(38_741_000, 4_096)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }

    fn clear_single_line_config() -> Weight {
        Weight::from_parts(35_218_000, 4_096)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }

    fn update_single_line_params() -> Weight {
        Weight::from_parts(41_523_000, 4_096)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }

    fn set_level_based_levels() -> Weight {
        Weight::from_parts(28_934_000, 3_584)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn remove_level_based_levels() -> Weight {
        Weight::from_parts(25_107_000, 3_584)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn force_set_single_line_config() -> Weight {
        Weight::from_parts(22_156_000, 3_072)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }

    fn force_clear_single_line_config() -> Weight {
        Weight::from_parts(19_843_000, 3_072)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }

    fn force_reset_single_line(s: u32) -> Weight {
        Weight::from_parts(18_247_000, 3_584)
            .saturating_add(Weight::from_parts(12_831_000_u64.saturating_mul(s as u64), 0))
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().reads(s as u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
            .saturating_add(RocksDbWeight::get().writes(s as u64))
    }

    fn pause_single_line() -> Weight {
        Weight::from_parts(21_432_000, 3_072)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn resume_single_line() -> Weight {
        Weight::from_parts(21_432_000, 3_072)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn schedule_config_change() -> Weight {
        Weight::from_parts(36_218_000, 4_096)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn apply_pending_config() -> Weight {
        Weight::from_parts(42_617_000, 4_608)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(4_u64))
    }

    fn cancel_pending_config() -> Weight {
        Weight::from_parts(24_316_000, 3_072)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn force_remove_from_single_line() -> Weight {
        Weight::from_parts(16_892_000, 2_560)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
}
