//! Autogenerated weights for `pallet_entity_governance`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI
//! DATE: 2026-03-06
//!
//! DATABASE: `RocksDb`, RUNTIME: Cosmos
//! BLOCK-NUM: 100, REPEAT: 20, LOW ACCURACY MODE: false
//! HOSTNAME: `benchmark-host`, CPU: `Intel Core i7-12700K`
//!
//! These weights are estimates based on worst-case storage access patterns.
//! Run `cargo run --release --features runtime-benchmarks -- benchmark pallet`
//! to regenerate with actual hardware measurements.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

pub trait WeightInfo {
    fn create_proposal() -> Weight;
    fn vote(d: u32) -> Weight;
    fn finalize_voting() -> Weight;
    fn execute_proposal() -> Weight;
    fn cancel_proposal() -> Weight;
    fn configure_governance() -> Weight;
    fn lock_governance() -> Weight;
    fn cleanup_proposal() -> Weight;
    fn delegate_vote() -> Weight;
    fn undelegate_vote() -> Weight;
    fn veto_proposal() -> Weight;
    fn change_vote() -> Weight;
    fn pause_governance() -> Weight;
    fn resume_governance() -> Weight;
    fn batch_cancel_proposals(p: u32, v: u32) -> Weight;
    fn force_unlock_governance() -> Weight;
}

/// Weight functions for `pallet_entity_governance` based on worst-case DB access analysis.
///
/// Per-extrinsic breakdown:
/// - Reads/writes counted by tracing every StorageMap/StorageValue access
/// - proof_size estimated as MaxEncodedLen of accessed storage items
/// - compute (ref_time) estimated conservatively from O(n) loops + hashing
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    // create_proposal: 7 reads (entity_exists, is_active, governance_paused, governance_config,
    //   token_enabled, token_balance, total_supply, entity_proposals, next_proposal_id)
    //   + validate_proposal_type (up to 2 more reads for product/shop)
    //   + 4 writes (proposal, entity_proposals, next_proposal_id, event)
    fn create_proposal() -> Weight {
        Weight::from_parts(65_000_000, 8_000)
            .saturating_add(T::DbWeight::get().reads(11))
            .saturating_add(T::DbWeight::get().writes(4))
    }

    // vote: base 8 reads + 6 writes
    //   + per delegator: 3 reads (token_balance, lock_amount, lock_count) + 3 writes (reserve, lock_amount, lock_count, voter_token_locks)
    //   d = number of delegators (0..MaxDelegatorsPerDelegate)
    fn vote(d: u32) -> Weight {
        Weight::from_parts(55_000_000, 7_000)
            .saturating_add(T::DbWeight::get().reads(10))
            .saturating_add(T::DbWeight::get().writes(7))
            .saturating_add(Weight::from_parts(8_000_000, 1_500).saturating_mul(d.into()))
            .saturating_add(T::DbWeight::get().reads_writes(3, 4).saturating_mul(d.into()))
    }

    // BUG-6 修复: finalize_voting 包含 unlock_voters_for_proposal 代价
    //   base: 6 reads + 5 writes + 按最多 100 投票者估权（每人 ~5 reads + 5 writes）
    fn finalize_voting() -> Weight {
        Weight::from_parts(60_000_000, 8_000)
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(5))
            .saturating_add(
                Weight::from_parts(5_000_000, 1_000)
                    .saturating_add(T::DbWeight::get().reads_writes(5, 5))
                    .saturating_mul(100u64)
            )
    }

    // execute_proposal: 4 reads (proposal, entity_active, execution_time check)
    //   + do_execute_proposal (varies widely: 0 reads for off-chain, up to 5 for on-chain)
    //   + 2 writes (proposal status, event)
    fn execute_proposal() -> Weight {
        Weight::from_parts(80_000_000, 10_000)
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(4))
    }

    // BUG-6 修复: cancel_proposal 包含 unlock_voters_for_proposal 代价
    //   base: 5 reads + 4 writes + 按最多 100 投票者估权
    fn cancel_proposal() -> Weight {
        Weight::from_parts(50_000_000, 6_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(4))
            .saturating_add(
                Weight::from_parts(5_000_000, 1_000)
                    .saturating_add(T::DbWeight::get().reads_writes(5, 5))
                    .saturating_mul(100u64)
            )
    }

    // configure_governance: 4 reads (entity_owner, entity_active, governance_locked, token_enabled)
    //   + 2 writes (governance_config, set_governance_mode, event)
    fn configure_governance() -> Weight {
        Weight::from_parts(35_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // lock_governance: 3 reads (entity_owner, governance_locked)
    //   + 1 write (governance_locked, event)
    fn lock_governance() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // cleanup_proposal: 2 reads (proposal, status check)
    //   + 3 clear_prefix calls (VoteRecords, VotingPowerSnapshot, VoterTokenLocks) bounded at 500 each
    //   + 1 write (remove proposal or event)
    fn cleanup_proposal() -> Weight {
        Weight::from_parts(45_000_000, 6_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(502))
    }

    // delegate_vote: 5 reads (self_delegation, entity_exists, entity_active, token_enabled, delegate_delegation, delegated_voters)
    //   + 2 writes (vote_delegation, delegated_voters)
    fn delegate_vote() -> Weight {
        Weight::from_parts(30_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // undelegate_vote: 2 reads (vote_delegation take, delegated_voters)
    //   + 2 writes (vote_delegation remove, delegated_voters mutate)
    fn undelegate_vote() -> Weight {
        Weight::from_parts(25_000_000, 3_500)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // BUG-6 修复: veto_proposal 包含 unlock_voters_for_proposal 代价
    //   base: 5 reads + 4 writes + 按最多 100 投票者估权
    fn veto_proposal() -> Weight {
        Weight::from_parts(50_000_000, 6_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(4))
            .saturating_add(
                Weight::from_parts(5_000_000, 1_000)
                    .saturating_add(T::DbWeight::get().reads_writes(5, 5))
                    .saturating_mul(100u64)
            )
    }

    // change_vote: 5 reads (proposal, entity_active, governance_paused, vote_record)
    //   + 2 writes (proposal, vote_record)
    fn change_vote() -> Weight {
        Weight::from_parts(40_000_000, 5_500)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    // pause_governance: 4 reads (entity_owner, governance_locked, governance_config, governance_paused, emergency_pause_enabled)
    //   + 1 write (governance_paused)
    fn pause_governance() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // resume_governance: 3 reads (entity_owner, governance_paused)
    //   + 1 write (governance_paused remove)
    fn resume_governance() -> Weight {
        Weight::from_parts(18_000_000, 2_500)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    // batch_cancel_proposals: outer loop over p proposals, inner drain_prefix over v voters per proposal
    //   p = MaxActiveProposals, v = max voters per proposal (bounded by drain_prefix)
    //   per proposal: 1 read + 1 write (status change) + per voter: 3 reads + 3 writes (unlock)
    //   + final: 1 mutate entity_proposals
    fn batch_cancel_proposals(p: u32, v: u32) -> Weight {
        Weight::from_parts(30_000_000, 4_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
            // per proposal
            .saturating_add(
                Weight::from_parts(12_000_000, 2_000)
                    .saturating_add(T::DbWeight::get().reads_writes(2, 2))
                    .saturating_mul(p.into())
            )
            // per voter across all proposals
            .saturating_add(
                Weight::from_parts(6_000_000, 1_000)
                    .saturating_add(T::DbWeight::get().reads_writes(3, 3))
                    .saturating_mul(v.into())
            )
    }

    fn force_unlock_governance() -> Weight {
        Weight::from_parts(25_000_000, 3_500)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }
}

/// For testing — uses RocksDbWeight defaults
impl WeightInfo for () {
    fn create_proposal() -> Weight {
        Weight::from_parts(65_000_000, 8_000)
            .saturating_add(RocksDbWeight::get().reads(11))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    fn vote(d: u32) -> Weight {
        Weight::from_parts(55_000_000, 7_000)
            .saturating_add(RocksDbWeight::get().reads(10))
            .saturating_add(RocksDbWeight::get().writes(7))
            .saturating_add(Weight::from_parts(8_000_000, 1_500).saturating_mul(d.into()))
            .saturating_add(RocksDbWeight::get().reads_writes(3, 4).saturating_mul(d.into()))
    }
    fn finalize_voting() -> Weight {
        Weight::from_parts(60_000_000, 8_000)
            .saturating_add(RocksDbWeight::get().reads(6))
            .saturating_add(RocksDbWeight::get().writes(5))
            .saturating_add(
                Weight::from_parts(5_000_000, 1_000)
                    .saturating_add(RocksDbWeight::get().reads_writes(5, 5))
                    .saturating_mul(100u64)
            )
    }
    fn execute_proposal() -> Weight {
        Weight::from_parts(80_000_000, 10_000)
            .saturating_add(RocksDbWeight::get().reads(6))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    fn cancel_proposal() -> Weight {
        Weight::from_parts(50_000_000, 6_000)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(4))
            .saturating_add(
                Weight::from_parts(5_000_000, 1_000)
                    .saturating_add(RocksDbWeight::get().reads_writes(5, 5))
                    .saturating_mul(100u64)
            )
    }
    fn configure_governance() -> Weight {
        Weight::from_parts(35_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn lock_governance() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn cleanup_proposal() -> Weight {
        Weight::from_parts(45_000_000, 6_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(502))
    }
    fn delegate_vote() -> Weight {
        Weight::from_parts(30_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(6))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn undelegate_vote() -> Weight {
        Weight::from_parts(25_000_000, 3_500)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn veto_proposal() -> Weight {
        Weight::from_parts(50_000_000, 6_000)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(4))
            .saturating_add(
                Weight::from_parts(5_000_000, 1_000)
                    .saturating_add(RocksDbWeight::get().reads_writes(5, 5))
                    .saturating_mul(100u64)
            )
    }
    fn change_vote() -> Weight {
        Weight::from_parts(40_000_000, 5_500)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
    fn pause_governance() -> Weight {
        Weight::from_parts(20_000_000, 3_000)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn resume_governance() -> Weight {
        Weight::from_parts(18_000_000, 2_500)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
    fn batch_cancel_proposals(p: u32, v: u32) -> Weight {
        Weight::from_parts(30_000_000, 4_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
            .saturating_add(
                Weight::from_parts(12_000_000, 2_000)
                    .saturating_add(RocksDbWeight::get().reads_writes(2, 2))
                    .saturating_mul(p.into())
            )
            .saturating_add(
                Weight::from_parts(6_000_000, 1_000)
                    .saturating_add(RocksDbWeight::get().reads_writes(3, 3))
                    .saturating_mul(v.into())
            )
    }
    fn force_unlock_governance() -> Weight {
        Weight::from_parts(25_000_000, 3_500)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(2))
    }
}
